### ISSUE TITLE
Bug: TXT or bulk links in notepad no longer work

### ISSUE THREAD

**Issue by Gamer4Life2020** [nathom/streamrip#103]
## Bug Report

- `streamrip` version(s): [e.g. v0.6.3]
- Python version: [e.g. 3.9]
- OS: [Windows 10 21H1]

**Additional context/Screenshots**
<img width="657" alt="Streamrip 6 3 TXT DL" src="https://user-images.githubusercontent.com/36717721/123321919-3705bc00-d4f9-11eb-8cd5-677a9dcc033e.PNG">

**Comment by jcpit** [comment]
Try run the txt file through dos2unix which will change the carriage returns.
If that fixes it, will be a simple fix.

**Comment by nathom** [comment]
The traceback shows that Python read the text file as the urls with spaces in between the characters for some reason. Check your txt file again to make sure nothing fishy is going on.

Also, next time please copy and paste the traceback instead of taking a screenshot. Thanks.

**Comment by nathom** [comment]
Never mind, it was actually a bug with streamrip.

**Comment by Gamer4Life2020** [comment]
I tried dos2unix just to see and the issue persists, I saw you said it was with streamrip, but figured I would try anyways.
