### ISSUE TITLE
Bug: Incorrect bit_depth/sampling_rate [2]

### ISSUE THREAD

**Issue by zzzzzozzzzz** [nathom/streamrip#106]
## Bug Report
**Source**
Qobuz

**Current Behavior**
Incorrect `bit_depth`/`sampling_rate`

- The tool reports (filepaths) the chosen audio `quality` (config file) and not the actual one. 

**Command used:**

```bash
rip -u 'link'
```

**`streamrip` Configuration File (extracts):**
```bash
quality: 4
```
```
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
```

**Environment**

- `streamrip` version: 939bbf32de1885f2bdc9309965a0583f05af6ae7
- Python version: 3.9
- OS: Linux

**Comment by nathom** [comment]
Please add a copy of the actual config file and the actual command you used.

**Comment by zzzzzozzzzz** [comment]
> Please add a copy of the actual config file and the actual command you used.

Please go to dis. Thanks.
