### ISSUE TITLE
Feature Request: Add option to convert album art into user-specified dimensions

### ISSUE THREAD

**Issue by kbruh** [nathom/streamrip#113]
## Feature Request

It would be very useful to have an option to convert the original album art file down to a specific resolution determined by the user in the config file.

Also a note in the config file about what resolution thumbnail, small, large, and original sized album art would be useful as well (image below).

<img width="567" alt="IMG_0354" src="https://user-images.githubusercontent.com/63879539/124322495-66897980-db34-11eb-9431-fec9993cfe67.png">

**Comment by nathom** [comment]
The sizes keys don't map to a specific resolution. For example, on Tidal, `large` would be `640px` but on soundcloud it would be `540px`. 

I'll look into resizing cover art though.
