### ISSUE TITLE
Bug: Bad file names.

### ISSUE THREAD

**Issue by zzzzzozzzzz** [nathom/streamrip#121]
## Bug Report
**Source**
Qobuz

**Current Behavior**
The tool reports the header in the file name.
It often happens that the name of the header coincides with the name of the song therefore the tool should report only the title of the song to avoid subsequent edits. 

**Example:**

```bash
01. White Christmas White Christmas
```

**Environment**

- `streamrip` version: 5afcee7 | v0.7
- Python version: 3.9
- OS: Linux

**Comment by nathom** [comment]
Can you include an example link please? I don't understand what you mean by this.

**Comment by zzzzzozzzzz** [comment]
> Can you include an example link please? I don't understand what you mean by this.

All answers ond ds.
