### ISSUE TITLE
Bug: Your Title

### ISSUE THREAD

**Issue by AbdulMalek00** [nathom/streamrip#123]
## Bug Report

**Current Behavior**
its only downloading album cover (deezer and tidal ) 
**Command used:**
rip -u https://www.deezer.com/en/album/6612814

```bash
# Type the command that caused the bug here
```

**Expected behavior**

**`streamrip` Configuration File (find using `rip config -o`):**

```toml
# Paste the contents of config.toml here
# REMOVE YOUR CREDENTIALS
[your]
config = "file"
```

**Environment**

- `streamrip` version(s): [e.g. v0.5.2]
- Python version: [e.g. 3.8]
- OS: [e.g. OSX 10.13.4, Windows 10]

**Traceback**
```bash
# Paste the text that Python dumped on the error here
# Delete this section if there was no traceback
```

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![Screen_Shot_2021-07-25_at_2 17 51_AM](https://user-images.githubusercontent.com/87918302/126884092-270e03b4-d41c-4a0b-925e-a1d56180f6ab.png)

**Comment by AbdulMalek00** [comment]
sorry for not mentionin using mac os and python 3.9.6 
and when trying this command this happen 

![](https://cdn.discordapp.com/attachments/868616620556292136/868644303197597767/Screen_Shot_2021-07-25_at_2.02.10_AM.png)

![](https://cdn.discordapp.com/attachments/868616620556292136/868643393947967498/Screen_Shot_2021-07-25_at_1.58.34_AM.png)

![](https://cdn.discordapp.com/attachments/868616620556292136/868644911887573053/Screen_Shot_2021-07-25_at_2.04.32_AM.png)

**Comment by nathom** [comment]
I need you to do a couple of things so that I can help you out:
- In a new Terminal window, run `rip config -o`. This should open up a text editor with the config file. Paste the contents of that file in a comment.
- Paste the result from running `rip --version`
- Run `pip uninstall streamrip && pip install streamrip --upgrade` in the terminal (not inside the interactive Python session like you did above)

**Comment by AbdulMalek00** [comment]
1 - doesn't open it directly I have to search for this file manually config.toml 
[downloads]
# Folder where tracks are downloaded to
folder = ""
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrent = false

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

# Doesn't require login
[deezer]
# 0, 1, or 2
quality = 2

[soundcloud]
# Only 0 is available for now
quality = 0

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.
[database.downloads]
enabled = true
path = ""

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
[database.failed_downloads]
enabled = true
path = ""

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
max_width = 999999
max_height = 999999
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[misc]
# Check whether a newer version of streamrip is available when starting up
check_for_updates = true

# Metadata to identify this config file. Do not change.
version = "0.7.1"


2\3 -
![Screen_Shot_2021-07-25_at_5 14 23_PM](https://user-images.githubusercontent.com/87918302/126904200-cc9764ea-5528-406d-81b3-17d9bf09a2c1.png)
![Screen_Shot_2021-07-25_at_5 13 54_PM](https://user-images.githubusercontent.com/87918302/126904201-6468a958-29cd-43f8-a385-1262de3a9335.png)
![Screen_Shot_2021-07-25_at_5 12 36_PM](https://user-images.githubusercontent.com/87918302/126904203-58c83ef7-664f-404a-838c-6e527ced8ed9.png)

**Comment by nathom** [comment]
Ok now try to download something from soundcloud or tidal.

**Comment by AbdulMalek00** [comment]
Same issue sir 
![Screen_Shot_2021-07-25_at_10 55 38_PM](https://user-images.githubusercontent.com/87918302/126913392-e79d3200-54b3-4a62-898e-73812b34081e.png)
![Screen_Shot_2021-07-25_at_10 59 10_PM](https://user-images.githubusercontent.com/87918302/126913393-e1b399d4-b1e1-4dbb-a407-6092aa166549.png)
![Screen_Shot_2021-07-25_at_11 00 03_PM](https://user-images.githubusercontent.com/87918302/126913395-a88bf3fe-7199-47be-af34-d2804ecdf5b7.png)
![Screen_Shot_2021-07-25_at_11 01 30_PM](https://user-images.githubusercontent.com/87918302/126913396-b03f06a3-f8f7-4ae6-b5ef-d44a570c2666.png)
![Screen_Shot_2021-07-25_at_11 02 57_PM](https://user-images.githubusercontent.com/87918302/126913424-07cfae50-2cdb-4410-8efd-68cd0eec4200.png)

**Comment by nathom** [comment]
Ok, this is an issue with the way you installed Python. Try reinstalling it.

**Comment by AbdulMalek00** [comment]
hi 
I have uninstall / install python 3 , but I have same issue 
![Screen_Shot_2021-07-29_at_4 46 38_PM](https://user-images.githubusercontent.com/87918302/127513530-f9a12b56-1993-4739-b49a-d91c8b174cc2.png)

using os x El Capitan
