### ISSUE TITLE
Bug: Mixing different versions of same album if using artist id

### ISSUE THREAD

**Issue by Gamer4Life2020** [nathom/streamrip#127]
## Bug Report

**Current Behavior**
Mixing edited/explicit of same album when using artist id not album link.

**Expected behavior**
To download the proper album or versions in the correct folders.

**`streamrip` Configuration File (find using `rip config -o`):**

[downloads]
# Folder where tracks are downloaded to
folder = "F:\\Music DL"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = true
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrent = true

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = false

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

# Doesn't require login

[deezer]
# 0, 1, or 2
quality = 2

[soundcloud]
# Only 0 is available for now
quality = 0

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = "C:\\Users\\User\\AppData\\Roaming\\streamrip\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

[database.failed_downloads]
enabled = true
path = "C:\\Users\\User\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.

[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.

[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
max_width = 999999
max_height = 999999
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true

# Changes the folder and file names generated by streamrip.

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"

# Last.fm playlists are downloaded by searching for the titles of the tracks

[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[misc]
# Check whether a newer version of streamrip is available when starting up
check_for_updates = true

# Metadata to identify this config file. Do not change.
version = "0.7.1"

```toml
# Paste the contents of config.toml here
# REMOVE YOUR CREDENTIALS
[your]
config = "file"
```

**Environment**

- `streamrip` version(s): [e.g. v0.7.1]
- Python version: [e.g. 3.9]
- OS: [e.g. Windows 10]

**Possible Solution**
No sure on the available tags, but maybe besides name match albums off the catalog/barcode id, or put catalog/barcode
in the folder name?

**Additional context/Screenshots**
![Multi](https://user-images.githubusercontent.com/36717721/127515066-c2e3cde3-d06b-4fb0-8afb-c213981b6462.PNG)
![Edited](https://user-images.githubusercontent.com/36717721/127515089-4d4882ae-a82b-46f4-ad72-6f079642f18d.PNG)
![Explicit](https://user-images.githubusercontent.com/36717721/127515096-9c38f4b4-e913-4e2f-a360-9476414c4b2f.PNG)

**Comment by nathom** [comment]
Did you try using the repeats filter?

**Comment by Gamer4Life2020** [comment]
No, but did and they are not working even the example on the site.

C:\Users\User>rip filter --repeats --features 'https://open.qobuz.com/artist/22195'
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\rip.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\rip\cli.py", line 500, in main
    cli(obj={})
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\rip\cli.py", line 146, in filter_discography
    config.session["filters"] = filters
AttributeError: 'Command' object has no attribute 'session'

C:\Users\User>

I'll uninstall and reinstall and try again.

**Comment by Gamer4Life2020** [comment]
Uninstalled and manually removed leftover files, installed 7.1 and turned on:
# Picks the highest quality out of albums with identical titles.
repeats = true
# Remove albums whose artist is not the one requested
features = true

Trying again to see if it still happens.

**Comment by Gamer4Life2020** [comment]
Seems ok not not mixing tracks, but didn't pull the Explicit one pulled the Edited one. Unless the two are the same and no label on one...no biggie though.
