### ISSUE TITLE
[StreamRip 1.1] Config file not found

### ISSUE THREAD

**Issue by Poloche9x7** [nathom/streamrip#131]
## Bug Report

**Current Behavior**
Config file not found after updated tool from 0.71 to 1.1

**Command used:**

```bash
pip3 install streamrip --upgrade
rip config --open
```

**Expected behavior**
Config file not found with new version 1.1

**`streamrip` Configuration File (find using `rip config -o`):**

```toml
# Paste the contents of config.toml here
# REMOVE YOUR CREDENTIALS
[your]

error, can't check my config file...
```

**Environment**

- `streamrip` version(s): v1.1
- Python version: 3.9
- OS: Windows 10

**Traceback**
```bash
C:\Users\user>rip config --open

  FileNotFoundError

  [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Local\\streamrip\\streamrip\\config.toml'

  at c:\users\user\appdata\local\programs\python\python39\lib\shutil.py:264 in copyfile
       260│
       261│     if not follow_symlinks and _islink(src):
       262│         os.symlink(os.readlink(src), dst)
       263│     else:
    →  264│         with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
       265│             # macOS
       266│             if _HAS_FCOPYFILE:
       267│                 try:
       268│                     _fastcopy_fcopyfile(fsrc, fdst, posix._COPYFILE_DATA)

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

**Comment by khanh-ne** [comment]
Similar bug. I tried to create the folder for the config.toml but there is still an error with the shutil.py. No idea how to fix

**Comment by Poloche9x7** [comment]
You need to create path and copy your old config.toml in the directory.
After type : rip confil --open and the tool will replace your config file to the new :)

**Comment by khanh-ne** [comment]
> You need to create path and copy your old config.toml in the directory.
> After type : rip config --open and the tool will replace your config file to the new :)

Thanks, I successfully fixed it.
