### ISSUE TITLE
Bug: streamrip in new or wrong location

### ISSUE THREAD

**Issue by Gamer4Life2020** [nathom/streamrip#134]
## Bug Report

**Current Behavior**
[Errno 2] No such file or directory: 'C:\\Users\\MASTER\\AppData\\Local\\streamrip\\streamrip\\config.toml'

**Command used:**
rip config --open

**Expected behavior**
To work as before the update. It's wanting local now and not roaming and two streamrip folders.
So, I made a seconded streamrip folder and copeid to local and is fine.

**Additional context/Screenshots**
![strimrip wrong location](https://user-images.githubusercontent.com/36717721/127779981-db82e309-943d-4fd4-91c6-9a23813ae13a.PNG)

**Comment by Gamer4Life2020** [comment]
did rip url....logged in again and now has config under local not roaming and one folder instead of two.
So seems ok now, and could of just been an oversite on my part.

**Comment by fertigfutter** [comment]
I had the same problem. My streamrip folder was created here:
C:\Users\xyz\AppData\Local\Programs\Python\Python39\Lib\site-packages\streamrip
A folder called
C:\Users\xyz\AppData\Local\streamrip
did not exist. Had to create C:\Users\xyz\AppData\Local\streamrip\streamrip to put config.toml in there.

**Comment by nathom** [comment]
Fixed in `v1.2`.
