### ISSUE TITLE
Bug: Stuck.

### ISSUE THREAD

**Issue by zzzzzozzzzz** [nathom/streamrip#138]
## Bug Report

**Current Behavior**
When I try to download a record label, the tool stuck when it encounters an album with missing tracks.
The tool does not continue downloading the other releases.

**Environment**

- `streamrip` version: 04884272e0fc8618b0a637f207baa6a939bb071f
- Python version: 3.9
- OS: Linux

**Comment by nathom** [comment]
Fixed in `v1.3`.
