### ISSUE TITLE
Bug: [UnknownB-UnknownkHz]

### ISSUE THREAD

**Issue by zzzzzozzzzz** [nathom/streamrip#139]
## Bug Report
**Source**
Deezer

**Current Behavior**
The tool doesn't report `bit_depth` and `sampling_rate` (HiFi account).

**Command used:**

```bash
rip url https://www.deezer.com/...
```

**`streamrip` Configuration File (extracts):**
```bash
quality = 2
```

**Environment**

- `streamrip` version: 04884272e0fc8618b0a637f207baa6a939bb071f
- Python version: 3.9
- OS: Linux

**Comment by nathom** [comment]
Is this using deezloader or a paid deezer account?

**Comment by zzzzzozzzzz** [comment]
> Is this using deezloader or a paid deezer account?

HiFi account, a paid account.

**Comment by nathom** [comment]
It is showing the correct bit depth and sampling rate for me. Double check that you were using a valid HiFi account.

**Comment by zzzzzozzzzz** [comment]
Triple checked!
It is a HiFi account, it downloads FLAC files.

**Comment by nathom** [comment]
Fixed in `v1.3`.
