### ISSUE TITLE
Bug: Deezer Podcasts

### ISSUE THREAD

**Issue by jasondlouw** [nathom/streamrip#141]
## Bug Report

**Current Behavior**

I am using a deezer paid subscription with a validated arl.

Downloading music works from a playlist work as expected.

Attempting to download a podcast such as `https://www.deezer.com/en/show/724752` results in an error.

**Command used:**

```bash
# rip url https://www.deezer.com/en/show/724752
```

**Expected behavior**

The playlist of podcast episodes is downloaded.

**Configuration File Details**

Only changes are deezer arl token and download location

- Python version: 1.2

**Traceback**
```bash
AssertionError

  at ~/.local/lib/python3.9/site-packages/rip/core.py:202 in handle_item
      198│         if media_type not in MEDIA_TYPES:
      199│             if "playlist" in media_type:  # for SoundCloud
      200│                 media_type = "playlist"
      201│
    → 202│         assert media_type in MEDIA_TYPES, media_type
      203│         item = MEDIA_CLASS[media_type](client=client, id=item_id)
      204│         self.append(item)
      205│
      206│     def _get_download_args(self) -> dict:
```

**Comment by nathom** [comment]
Podcasts aren't supported as of now. I'm labeling this as an enhancement so that I can work on supporting it.

**Comment by jasondlouw** [comment]
Thank you for all your work on the project, it is greatly appreciated.

**Comment by R3AP3** [comment]
You can download Podcasts (it works best with spotify urls) via youtube-dl since they are not encrypted. Hope that helps. @jasondlouw
