### ISSUE TITLE
Resulting file size for Deezer is about 12 kb

### ISSUE THREAD

**Issue by inglesuniversal** [nathom/streamrip#142]
Installation gave no errors on MacOS 11.4 Big Sur

However, resulting file was about 12 kb in size

no subscription is yet enabled.

Any pointers?

**Comment by nathom** [comment]
What is the url you wanted to download?

**Comment by inglesuniversal** [comment]
Hello again

The url was...

rip url https://www.deezer.com/us/track/63480986

this was shown upon entering the command above....

Falling back to Deezloader (max 320kbps MP3). If you have a subscription, run rip config --deezer to download FLAC files.

....


I tried with another url and the result was the same... Do I need a subscription for this to work?  

Best regards

**Comment by nathom** [comment]
Fixed in `v1.3`.

**Comment by nathom** [comment]
Also note that the link you used was invalid. To download Second Hand News, use https://www.deezer.com/us/track/67549187 instead.

**Comment by inglesuniversal** [comment]
You rock!

Sample url worked like a charm... with the exception that no cover was apparently downloaded into the id3 tags.

If you want me to check any config file, please let me know.

Take care.

**Comment by nathom** [comment]
Unless you specified a max quality, it should have downloaded a FLAC file. Did it download an MP3 instead?

**Comment by inglesuniversal** [comment]
FLAC format is awesome for me because of the quality... and yes, I double checked and the cover was not downloaded on a single file but it is downloaded separately inside a folder (when getting a full album).

Is there a way to add a cover to a FLAC file by default?

Thanks again!
