### ISSUE TITLE
Bug: Wrong genre.

### ISSUE THREAD

**Issue by zzzzzozzzzz** [nathom/streamrip#147]
## Bug Report
**Source**
Deezer

**Current Behavior**
All releases downloaded from deezer contain commas in the metadata (genre). 

**Example**
```bash
J, a, z, z
```
**Environment**

- `streamrip` version: cb4415e896f4fa7799c129a7345ef56510ccb420
- Python version: 3.9
- OS: Linux

**Comment by nathom** [comment]
Fixed in `v1.3`.
