### ISSUE TITLE
[CONFIG] Keep actual config when update

### ISSUE THREAD

**Issue by Poloche9x7** [nathom/streamrip#151]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When we update the tool, config file is replaced by new file. We are losing all the config...

**Describe the solution you'd like**
May be, tool can only update new line on file, not replace all the line ?

Thanks

**Comment by nathom** [comment]
Due to the way the TOML parser works, I can only choose which lines to keep. Currently, only Qobuz and Tidal credentials are kept. I'm thinking of adding the following also:

- Downloads folder
- Deezer ARL
- `folder_format`
- `track_format`

Are there any other settings you want saved?

**Comment by Poloche9x7** [comment]
Download folder, Deezer Config, Qobuz Config, Tidal Config, Folder Format, Track Format and [database.downloads]

It will be nice :)

**Comment by Poloche9x7** [comment]
Greet works !! All it's ok when i updated to v1.4 :)

Thanks
