### ISSUE TITLE
Bug: v1.x fails to launch on M1 Mac

### ISSUE THREAD

**Issue by TL37** [nathom/streamrip#152]
## Bug Report

**Current Behavior**

Following upgrade to v1.x, streamrip fails to run on M1 Mac with the errors below. Reinstalling v0.7.1 resolves the issue.

Attempted to install using Terminal in Rosetta2 mode with similar result.

**Environment**

- `streamrip` version(s): v1.3 - tested v1.0 with same result
- Python version: 3.9.4
- OS: MacOS 11.5.1

**Traceback**
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/rip", line 5, in <module>
    from rip.cli import main
  File "/opt/homebrew/lib/python3.9/site-packages/rip/cli.py", line 12, in <module>
    from streamrip import __version__
  File "/opt/homebrew/lib/python3.9/site-packages/streamrip/__init__.py", line 5, in <module>
    from . import clients, constants, converter, media
  File "/opt/homebrew/lib/python3.9/site-packages/streamrip/clients.py", line 16, in <module>
    from Cryptodome.Cipher import AES
  File "/opt/homebrew/lib/python3.9/site-packages/Cryptodome/Cipher/__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/opt/homebrew/lib/python3.9/site-packages/Cryptodome/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_ecb", """
  File "/opt/homebrew/lib/python3.9/site-packages/Cryptodome/Util/_raw_api.py", line 297, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Trying '_raw_ecb.cpython-39-darwin.so': dlopen(/opt/homebrew/lib/python3.9/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.cpython-39-darwin.so, 6): image not found, Trying '_raw_ecb.abi3.so': dlopen(/opt/homebrew/lib/python3.9/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so, 6): no suitable image found.  Did find:
	/opt/homebrew/lib/python3.9/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so: mach-o, but wrong architecture
	/opt/homebrew/lib/python3.9/site-packages/Cryptodome/Cipher/_raw_ecb.abi3.so: mach-o, but wrong architecture, Trying '_raw_ecb.so': dlopen(/opt/homebrew/lib/python3.9/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.so, 6): image not found

```

**Comment by nathom** [comment]
Are you running homebrew under rosetta?

**Comment by nathom** [comment]
Try installing the latest version of streamrip and running `arch -x86_64 rip`.

**Comment by TL37** [comment]
I reinstalled homebrew using Rosetta and am running my terminal under Rosetta also. The `arch` command shows `i386`. So, I think so, but I’m a novice and could be missing something.

This is what I get when I run `arch -x86_64 rip`:

`arch: posix_spawnp: rip: Bad CPU type in executable`

**Comment by nathom** [comment]
Maybe you don't have rosetta 2 installed. Try running

```
softwareupdate --install-rosetta
```

**Comment by TL37** [comment]
It was definitely installed but I ran the command anyway and am still getting the same errors.

Seems like you're thinking it's a homebrew issue?

**Comment by nathom** [comment]
It's difficult for me to pinpoint the issue exactly since I don't have an M1. All I know is that `streamrip` does work if it's setup properly.

Since the issue seems to be that PyCryptodome isn't compiling for arm64, you can try compiling the library from source 

```bash
# download source code
git clone https://github.com/Legrandin/pycryptodome
# compile and install
cd pycryptodome
pip3 install .
# test whether it works
python3 -m Cryptodome.SelfTest
```

If the test passes, then the library has been installed correctly. Let me know if this works.

**Comment by TL37** [comment]
The test didn’t pass, but after I tried that I tried uninstalling and reinstalling Homebrew and Python3 and it does now run correctly when I log in using `arch -x86_64`. I appreciate the help and thanks for building this very cool and useful tool.
