### ISSUE TITLE
Feature Request: Album ID numbers in title

### ISSUE THREAD

**Issue by Area0077** [nathom/streamrip#154]
## Feature Request

**Is your feature request related to a problem? Please describe.**
duplicate albums is failing the process and halting script, cannot repair or restart script with messages that albums already exist.

**Describe the solution you'd like**
implement existing album number to the title of the album or single, this way it will copy all regardless of duplicates

**Describe alternatives you've considered**

**Comment by nathom** [comment]
What are the links to the duplicate albums?

**Comment by nathom** [comment]
Added in `v1.5`.
