### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by R3AP3** [nathom/streamrip#161]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Sometimes when i download something and it contains special characters (for example russian ones) i had problems to get them off my server in the past. A setting so that streamrip scrictly only tags normal characters would be cool.

**Describe the solution you'd like**
A true/false setting in the config.toml to restrict file name characters. (or an argument like --restrict-filenames that youtube-dl has)

**Describe alternatives you've considered**
Well searched but right now theres no better all pourpose download tool out there. Thanks for your work.

**Comment by nathom** [comment]
Fixed in `v1.5`.
