### ISSUE TITLE
Feature Request: execute command after finish

### ISSUE THREAD

**Issue by R3AP3** [nathom/streamrip#162]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Executing a set command after downloading is finished

**Describe the solution you'd like**
You could make a setting in the config for example "execute after finish = 'cool command'"
via an argument "--execute-command 'cool command'"

would be cool for automating tasks other than encoding after finish.

Have a great day :)

**Comment by nathom** [comment]
If you want to encode tracks, use the conversion options in the config file. For any other command you can do something like `rip url https://mytrack.com && my-cool-command`. This will execute `my-cool-command` after `rip` finishes executing.

**Comment by R3AP3** [comment]
Well the && is possible correct. But what would be cool is if you could set the command that finishes after executing in the config file. That way you dont have to type it in the command line over and over again. And no its not for encoding i know that that is possible via the config settings. 

Thank you :)

**Comment by nathom** [comment]
For that, you would use a function. For example, in bash you can do

```bash
function myrip() {
    rip $@ && echo 'execute whatever you want'
}
```

but replace the `echo` with the command you want. You can put the function in `.profile` so that it is defined every time you open up a terminal. You will be able to use `myrip` just as you would use `rip`.
