### ISSUE TITLE
Feature Request:  GUI - Web interface

### ISSUE THREAD

**Issue by Sherzod2000** [nathom/streamrip#170]
## Feature Request

**Better GUI solution**
Hello, it is not always convenient to work with the terminal, it is much more convenient to work through the browser through the terminal, the terminal is in all platforms, the browser is also in all platforms, so you win in everything

**How can this be realized ?!**
Implement via Webserver - localhost.

Here is an example of how it will look: The user enters the terminal, enters rip gui [port number, for example], enters the browser enters localhost: port, and a web interface comes out with the following options: there will be buttons for selecting quality, search, setting Steamrip, and exiting

**Comment by Sherzod2000** [comment]
the base for this can be the Chimera music downloader project

**Comment by nathom** [comment]
That's beyond the scope of this project. If someone else wants to implement a web interface for streamrip in a separate repository, they are welcome to.
