### ISSUE TITLE
Bug: Unable to download albums from deezer free account.

### ISSUE THREAD

**Issue by klvilo** [nathom/streamrip#172]
I am trying to download a album from Deezer (free account). and it gives me error. Can you please help? i even try to put arl number in confg.toml file but still the same error.

This is the command that i used:
rip url https://www.deezer.com/us/album/56745872
-------------------------------------------------------------
UnexpectedCharError

  Unexpected character: 'C' at line 3 col 11

  at ~\AppData\Local\Programs\Python\Python39\lib\site-packages\tomlkit\parser.py:348 in _parse_comment_trail
       344│                 break
       345│             elif c in " \t\r":
       346│                 self.inc()
       347│             else:
    →  348│                 raise self.parse_error(UnexpectedCharError, c)
       349│
       350│             if self.end():
       351│                 break
       352│

**Comment by nathom** [comment]
Can you paste your config here?

**Comment by klvilo** [comment]
Here is the config.toml file you asked:
[config.txt](https://github.com/nathom/streamrip/files/7144281/config.txt)

**Comment by nathom** [comment]
@zzzzzozzzzz Deezloader still works for me. I tried it with the link in this issue.

**Comment by klvilo** [comment]
What should i do now? No service is available in my country Tidal, Deezer, Qobuz Nothing. i cant buy their subscription.

**Comment by nathom** [comment]
@klvilo You should probably use a VPN that changes your location to another country, and buy a subscription under the new location.

Are you still getting the `tomlkit` error? Your config seems fine.
