### ISSUE TITLE
error run it un termux (android)

### ISSUE THREAD

**Issue by noob-eng** [nathom/streamrip#173]
rip search --source deezer 'copines'

dlopen failed: library "libc.so.6" not found

  at /data/data/com.termux/files/usr/lib/python3.9/ctypes/__init__.py:374 in __init__
      370│             _restype_ = self._func_restype_
      371│         self._FuncPtr = _FuncPtr
      372│
      373│         if handle is None:
    → 374│             self._handle = _dlopen(self._name, mode)
      375│         else:
      376│             self._handle = handle
      377│
      378│     def __repr__(self):

The following error occurred when trying to handle this error:

                                                                                AssertionError

                                                                              
  at /data/data/com.termux/files/usr/lib/python3.9/site-packages/simple_term_menu.py:1348 in _clear_menu
      1344│
      1345│     def _clear_menu(self) -> None:
      1346│         # pylint: disable=unsubscriptable-object
      1347│         assert self._codename_to_terminal_code is not None
    → 1348│         assert self._previous_displayed_menu_height is not None
      1349│         assert self._tty_out is not None
      1350│         if self._clear_menu_on_exit:
      1351│             if self._title_lines:
      1352│                 self._tty_out.write(len(self._title_lines) * self._codename_to_terminal_code["cursor_up"])

**Comment by nathom** [comment]
This is because your android terminal doesn't support UI based apps. I'll look into adding an alternative for `rip search`.

**Comment by noob-eng** [comment]
thanks
