### ISSUE TITLE
[BUG] Received InvalidUnicodeValueError

### ISSUE THREAD

**Issue by jlgarnier** [nathom/streamrip#185]
### Describe the bug

Hi,

The script looks great and I tested it on a Win10 machine with Python 3.9.4. I tried to download an album from Deezer (token set) and got the following error message:
`
InvalidUnicodeValueError

Invalid unicode value at line 3 col 13

at C:\Program Files\Python39\lib\site-packages\tomlkit\parser.py:897 in _parse_escaped_char
893│ self.inc_n(len(ue) + 1)
894│
895│ return u
896│
→ 897│ raise self.parse_error(InvalidUnicodeValueError)
898│
899│ raise self.parse_error(InvalidCharInStringError, self._current)
900│
901│ def _parse_string(self, delim): # type: (StringType) -> String

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose`

Does this relate to my local config or is there anything I should further configure in the .oml file?

Thanks in advance for any help!

### Command Used

```bash
rip url https://www.deezer.com/fr/album/247571742
```

### Debug Traceback

```text
Stack trace:

  18  C:\Program Files\Python39\lib\site-packages\cleo\application.py:314 in run
        exit_code = self._run(io)

  17  C:\Program Files\Python39\lib\site-packages\rip\cli.py:624 in _run
        super()._run(io)

  16  C:\Program Files\Python39\lib\site-packages\cleo\application.py:409 in _run
        exit_code = self._run_command(command, io)

  15  C:\Program Files\Python39\lib\site-packages\cleo\application.py:416 in _run_command
        return command.run(io)

  14  C:\Program Files\Python39\lib\site-packages\cleo\commands\base_command.py:118 in run
        status_code = self.execute(io)

  13  C:\Program Files\Python39\lib\site-packages\cleo\commands\command.py:85 in execute
        return self.handle()

  12  C:\Program Files\Python39\lib\site-packages\rip\cli.py:55 in handle
        config = Config()

  11  C:\Program Files\Python39\lib\site-packages\rip\config.py:59 in __init__
        self.load()

  10  C:\Program Files\Python39\lib\site-packages\rip\config.py:141 in load
        for k, v in tomlkit.loads(cfg.read().strip()).items():

   9  C:\Program Files\Python39\lib\site-packages\tomlkit\api.py:34 in loads
        return parse(string)

   8  C:\Program Files\Python39\lib\site-packages\tomlkit\api.py:51 in parse
        return Parser(string).parse()

   7  C:\Program Files\Python39\lib\site-packages\tomlkit\parser.py:160 in parse
        key, value = self._parse_table()

   6  C:\Program Files\Python39\lib\site-packages\tomlkit\parser.py:1154 in _parse_table
        item = self._parse_item()

   5  C:\Program Files\Python39\lib\site-packages\tomlkit\parser.py:306 in _parse_item
        return self._parse_key_value(True)

   4  C:\Program Files\Python39\lib\site-packages\tomlkit\parser.py:397 in _parse_key_value
        val = self._parse_value()

   3  C:\Program Files\Python39\lib\site-packages\tomlkit\parser.py:561 in _parse_value
        return self._parse_basic_string()

   2  C:\Program Files\Python39\lib\site-packages\tomlkit\parser.py:854 in _parse_basic_string
        return self._parse_string(StringType.SLB)

   1  C:\Program Files\Python39\lib\site-packages\tomlkit\parser.py:990 in _parse_string
        value += self._parse_escaped_char(delim.is_multiline())

  InvalidUnicodeValueError

  Invalid unicode value at line 3 col 13

  at C:\Program Files\Python39\lib\site-packages\tomlkit\parser.py:897 in _parse_escaped_char
       893│                 self.inc_n(len(ue) + 1)
       894│
       895│                 return u
       896│
    →  897│             raise self.parse_error(InvalidUnicodeValueError)
       898│
       899│         raise self.parse_error(InvalidCharInStringError, self._current)
       900│
       901│     def _parse_string(self, delim):  # type: (StringType) -> String

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
InvalidUnicodeValueError

  Invalid unicode value at line 3 col 13

  at C:\Program Files\Python39\lib\site-packages\tomlkit\parser.py:897 in _parse_escaped_char
       893│                 self.inc_n(len(ue) + 1)
       894│
       895│                 return u
       896│
    →  897│             raise self.parse_error(InvalidUnicodeValueError)
       898│
       899│         raise self.parse_error(InvalidCharInStringError, self._current)
       900│
       901│     def _parse_string(self, delim):  # type: (StringType) -> String

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Operating System

Windows 10

### streamrip version

1.5

### Additional context

I've edited the config file (first rip config --open command worked properly) with Notepad++, maybe the encoding should be fixed but I unfortunately cannot find the config file in the directory tree so I can't fix it manually.

**Comment by nathom** [comment]
There is an error in your `config.toml` file. Please paste the contents here so that I can see what's going on. Remember to remove your personal information before posting it.

**Comment by jlgarnier** [comment]
Hi Nathom,

Here you have! The only thing I edited is the Deezer tag:

`[downloads]
# Folder where tracks are downloaded to
folder = "C:\Users\jlgarnier\Music\_download"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = "my-token"
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.
[database.downloads]
enabled = true
path = ""

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
[database.failed_downloads]
enabled = true
path = ""

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# "id", and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"

[misc]
# Metadata to identify this config file. Do not change.
version = "1.5"
`

Thanks a lot for your help!

**Comment by jlgarnier** [comment]
Hi Nathan,

Did you find what should be fixed in my config file or did this reveal any bug in the code?

Thanks in advance for your help!

**Comment by nathom** [comment]
Hi, apologies for the delay. You need to escape the backslashes in the downloads directory. You can see the error when turning on the TOML syntax highlighting.
```toml
folder = "C:\Users\jlgarnier\Music\_download"
```

Change the downloads directory to

```toml
folder = "C:\\Users\\jlgarnier\\Music\\_download"
```

**Comment by jlgarnier** [comment]
Hi Nathan,

Thanks for the tip, I got a bit further with this! 😉 Anyway, launching the same command `rip url https://www.deezer.com/fr/album/247571742 -vv` as an example, here's what I got:
`Downloading WAIRUNGA (Album)

Downloading cover art (large)
Cover |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 00:00 left at 12.3MB/s

Unable to stream Fat Freddy's Drop - Coffee Black. Message:
Unable to stream Fat Freddy's Drop - Bones. Message:
Unable to stream Fat Freddy's Drop - Shady. Message:
Unable to stream Fat Freddy's Drop - Wairunga Blues. Message:
Unable to stream Fat Freddy's Drop - Bush Telegraph. Message:
Unable to stream Fat Freddy's Drop - Leave Your Window Open. Message:
Unable to stream Fat Freddy's Drop - Dig Deep. Message:`

So, no error message and I don't really get what happens... Thanks in advance for your help!

**Comment by nathom** [comment]
Did you log into your deezer account? It seems like you're using Deezloader, which is unreliable.

**Comment by jlgarnier** [comment]
Hi Nathom,
I don't understand your question: what do you mean by "Did you log into your deezer account"? Actually, I can log into Deezer website with the common login/password and I've correctly grabbed the token value from this webpage.
Regarding Deezloader, this app is indeed installed on my PC but I don't use it at the same time as Streamrip: should I uninstall it to get the script working?
Thanks in advance for your advice!

**Comment by nathom** [comment]
I meant to ask whether you logged into your deezer account in streamrip using `rip config --deezer`.

**Comment by jlgarnier** [comment]
Yes, and I received a `Sucessfully logged in!` message. What could then prevent the script from grabbing the files? What's the side effect with Deezloader?

**Comment by jlgarnier** [comment]
Hi Nathom,

Have some minutes left, I've upgraded streamrip to the version 1.7 and now get an error when trying to launch the app:
```
C:\Users\jlgarnier\Documents> rip
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\rip.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python310\lib\site-packages\rip\cli.py", line 15, in <module>
    from .core import RipCore
  File "C:\Program Files\Python310\lib\site-packages\rip\core.py", line 87, in <module>
    class RipCore(list):
  File "C:\Program Files\Python310\lib\site-packages\rip\core.py", line 93, in RipCore
    "deezer": DeezerClient(),
  File "C:\Program Files\Python310\lib\site-packages\streamrip\clients.py", line 448, in __init__
    self.client = deezer.Deezer(accept_language="en-US,en;q=0.5")
TypeError: Deezer.__init__() got an unexpected keyword argument 'accept_language'
```
Did anyone else stumble on this? Is there any procedure to upgrade the config file too (it still displays `version = "1.5"`)?

Thanks in advance for your help!
