### ISSUE TITLE
[FEATURE] add explicit to folder for better sorting discographies with explicit/clean

### ISSUE THREAD

**Issue by Gamer4Life2020** [nathom/streamrip#192]
### Is the feature request related to a problem. Please describe it.

No Issues

### Describe the solution you would like.

Would like to be able to add [explicit] or [E] to folder for explicit albums

### Describe alternatives you've considered.

Tried {explicit} with no luck

**Comment by nathom** [comment]
This should already work. Which link did you use?

**Comment by Gamer4Life2020** [comment]
Really any like that is explicit. Most resent one: https://play.qobuz.com/album/i8859pfty1gvb

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# "id", and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = true

I can add {explicit} to the end of the folder_format, but then it just has whatever {explicit} on every folder.
