### ISSUE TITLE
[BUG] Can't Install streamrip

### ISSUE THREAD

**Issue by Slawaspr0** [nathom/streamrip#203]
### Describe the bug

When I'm trying install streamrip 1.6 im getting error:

ERROR: Could not find a version that satisfies the requirement windows-curses<3.0.0,>=2.2.0; sys_platform == "win32" or sys_platform == "cygwin" (from streamrip) (from versions: none)
ERROR: No matching distribution found for windows-curses<3.0.0,>=2.2.0; sys_platform == "win32" or sys_platform == "cygwin"

Python 3.10.0
Windows 10 Home x64, 20H2, 19042.746

### Command Used

```bash
pip install streamrip==1.6
pip3 install streamrip==1.6
```

### Debug Traceback

```text
C:\>pip install streamrip==1.6
Collecting streamrip==1.6
  Using cached streamrip-1.6-py3-none-any.whl (83 kB)
Requirement already satisfied: pathvalidate<3.0.0,>=2.4.1 in c:\users\slawas\appdata\local\programs\python\python310\lib\site-packages (from streamrip==1.6) (2.5.0)
Collecting aiohttp<4.0.0,>=3.7.4
  Using cached aiohttp-3.7.4.post0.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing wheel metadata (pyproject.toml) ... done
Requirement already satisfied: mutagen<2.0.0,>=1.45.1 in c:\users\slawas\appdata\local\programs\python\python310\lib\site-packages (from streamrip==1.6) (1.45.1)
Collecting aiodns<4.0.0,>=3.0.0
  Using cached aiodns-3.0.0-py3-none-any.whl (5.0 kB)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in c:\users\slawas\appdata\local\programs\python\python310\lib\site-packages (from streamrip==1.6) (1.4.4)
Requirement already satisfied: pycryptodomex<4.0.0,>=3.10.1 in c:\users\slawas\appdata\local\programs\python\python310\lib\site-packages (from streamrip==1.6) (3.11.0)
Collecting aiofiles<0.8.0,>=0.7.0
  Using cached aiofiles-0.7.0-py3-none-any.whl (13 kB)
Requirement already satisfied: click<9.0.0,>=8.0.1 in c:\users\slawas\appdata\local\programs\python\python310\lib\site-packages (from streamrip==1.6) (8.0.3)
Requirement already satisfied: cleo==1.0.0a3 in c:\users\slawas\appdata\local\programs\python\python310\lib\site-packages (from streamrip==1.6) (1.0.0a3)
Requirement already satisfied: tqdm<5.0.0,>=4.61.1 in c:\users\slawas\appdata\local\programs\python\python310\lib\site-packages (from streamrip==1.6) (4.62.3)
Collecting m3u8<0.10.0,>=0.9.0
  Using cached m3u8-0.9.0-py3-none-any.whl (22 kB)
Collecting cchardet<3.0.0,>=2.1.7
  Using cached cchardet-2.1.7.tar.gz (653 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: deezer-py<2.0.0,>=1.0.4 in c:\users\slawas\appdata\local\programs\python\python310\lib\site-packages (from streamrip==1.6) (1.2.5)
ERROR: Could not find a version that satisfies the requirement windows-curses<3.0.0,>=2.2.0; sys_platform == "win32" or sys_platform == "cygwin" (from streamrip) (from versions: none)
ERROR: No matching distribution found for windows-curses<3.0.0,>=2.2.0; sys_platform == "win32" or sys_platform == "cygwin"

C:\>pip3 install streamrip==1.6
Collecting streamrip==1.6
  Using cached streamrip-1.6-py3-none-any.whl (83 kB)
Requirement already satisfied: click<9.0.0,>=8.0.1 in c:\users\slawas\appdata\local\programs\python\python310\lib\site-packages (from streamrip==1.6) (8.0.3)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in c:\users\slawas\appdata\local\programs\python\python310\lib\site-packages (from streamrip==1.6) (1.4.4)
Collecting aiodns<4.0.0,>=3.0.0
  Using cached aiodns-3.0.0-py3-none-any.whl (5.0 kB)
Collecting cchardet<3.0.0,>=2.1.7
  Using cached cchardet-2.1.7.tar.gz (653 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pycryptodomex<4.0.0,>=3.10.1 in c:\users\slawas\appdata\local\programs\python\python310\lib\site-packages (from streamrip==1.6) (3.11.0)
ERROR: Could not find a version that satisfies the requirement windows-curses<3.0.0,>=2.2.0; sys_platform == "win32" or sys_platform == "cygwin" (from streamrip) (from versions: none)
ERROR: No matching distribution found for windows-curses<3.0.0,>=2.2.0; sys_platform == "win32" or sys_platform == "cygwin"
```

### Config File

```toml
no config file
```

### Operating System

Windows 10 x64

### streamrip version

1.6

**Comment by nathom** [comment]
Do you have the latest version of Python?

**Comment by Slawaspr0** [comment]
Yes, 3.10.0, installed for streamrip yesterday. Fresh version.

**Comment by Slawaspr0** [comment]
Unfortunately 1.7 is still not working on 3.10
I uninstalled pytahon 3.9, install 3.10, and when i use command:
pip3 install streamrip --upgrade
it install streamrip1.1 as default, and i can't even run this version because I'm getting errors
when i force to install 1.7 using command:
pip3 install streamrip==1.7
getting errors like before "Could not find a version that satisfies the requirement windows..... [etc]"

For me also streamrip 1.6 on python 3.9 not working
When I installed python 3.9, and streamrip 1.6 and write command "rip" this appears:
Rip (version 1.6) [etc... etc...]
I though its gonna work, but I didn't test it further
Today i was trying to download something from Tidal
First i was trying to open config file and see whats there, i typed command: 
rip config --open
and config was opened, but only once, when i was trying open it again, error appear:

InvalidCharInStringError

  Invalid character '1' in string at line 3 col 13

  at c:\users\slawas\appdata\local\programs\python\python39\lib\site-packages\tomlkit\parser.py:899 in _parse_escaped_char
       895│                 return u
       896│
       897│             raise self.parse_error(InvalidUnicodeValueError)
       898│
    →  899│         raise self.parse_error(InvalidCharInStringError, self._current)
       900│
       901│     def _parse_string(self, delim):  # type: (StringType) -> String
       902│         # only keep parsing for string if the current character matches the delim
       903│         if self._current != delim.unit:

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose

And when I'm trying to do anything, like: "rip url https://tidal.com/browse/album/47357291" or anything, same error appear, can do nothing

**Comment by roher-dotcom** [comment]
Streamrip 1.7 is working fine on python 3.9 for me... Try to uninstall
streamrip and install again..may be this work for u

**Comment by Keysz** [comment]
I had the same error with Python 3.11.8 on Windows 11

**Comment by univon** [comment]
can somebody help me with the cygwin error!!!
