### ISSUE TITLE
Cannot open config file in Terminal on macOS Mojave 10.14.6

### ISSUE THREAD

**Issue by bern-dog** [nathom/streamrip#21]
rip config -o and rip config —o do not seem to do anything.

rip config —help properly displays the options, -q and —qobuz also properly prompt new credentials.

Mainly looking to change config for folder and track naming. Thanks!

EDIT: I found config.yaml and could manually edit and save some changes, but folder and track naming don't seem to take effect. I changed it to this and it still downloads in the default naming structure (with artist name, container, etc):

`path_format:
  folder: '({year}) {title} [{bit_depth}bit {sampling_rate}kHz]'
  track: '{tracknumber}. {title}'
`

**Comment by nathom** [comment]
I'm not sure why `rip config -o` doesn't work for you. The config file is located in `~/Library/Application Support/streamrip/config.yaml`, so you can open that in a text editor and change the fields.

**Comment by bern-dog** [comment]
> I'm not sure why `rip config -o` doesn't work for you. The config file is located in `~/Library/Application Support/streamrip/config.yaml`, so you can open that in a text editor and change the fields.

Thanks for the advice, I went ahead and did that and was able to change most things except for path_format. Everything else worked fine. When I changed it all I did was change what was between the ' marks, like so:

`path_format:
  folder: '({year}) {title} [{bit_depth}bit {sampling_rate}kHz]'
  track: '{tracknumber}. {title}'
`

and I kept the same line breaks as the default config file. Any ideas? Thanks!
