### ISSUE TITLE
[FEATURE] Make "(explicit)" name extension optional

### ISSUE THREAD

**Issue by Frnot** [nathom/streamrip#216]
### Is the feature request related to a problem. Please describe it.

There is currently no way to disable appending (Explicit) to the title of every track in an album marked explicit

### Describe the solution you would like.

I would like there to be a config option that allows us to disable "(Explicit)" being automatically added to track titles

### Describe alternatives you've considered.

I could remove these sections from the source code and run my modified version, but I would like there to be an easier option.

**Comment by Poloche9x7** [comment]
I need your moded version please !!! @nathom please add the option to allow/disallow explicit tag ! thanks

**Comment by nathom** [comment]
@Poloche9x7 Follow the instructions in the README for installing the dev branch.

**Comment by Frnot** [comment]
@Poloche9x7 does v1.7 not include this feature?

**Comment by Poloche9x7** [comment]
@nathom I have already instal the dev branch, but explicit tag is on when i download track from qobuz ! How to remove it ? thanks

My config file : 

# and "albumcomposer"
track_format = "{tracknumber}-{artist}-{title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false

**Comment by Rekulous** [comment]
> @Poloche9x7 Follow the instructions in the README for installing the dev branch.

The Dev branch already has a setting or removes the (Explicit) tag?
