### ISSUE TITLE
[FEATURE] Tidal supporting and downloading 24bit 96khz audio

### ISSUE THREAD

**Issue by SI0209** [nathom/streamrip#217]
### Is the feature request related to a problem. Please describe it.

I have an issue with trying to download Tidal music in 24bit 96khz. On your README.md file, it says it supports Tidal music up to 24bit 96khz. I've tried downloading two albums in an MQA and it only downloads up to 24bit 44.1khz. Meanwhile on programs like RedSea. I tried those two links and both downloaded at 24bit 48khz (even though only 1 is limited up to 24bit 48khz, but on other platforms like QoBuz, the other link would've downloaded at 96khz, and I'm pretty sure Tidal would've downloaded it in 24bit 96khz because it supports up to 24bit 192khz.

### Describe the solution you would like.

I would like streamrip to check for tidal links that support 96khz audio and download those audios from the links to test if the program supports 96khz audio, then send me those links to try getting it downloaded in 96khz. If they do download in 96khz, it means the links I tried do not support 96khz, but if they do not download in 96khz, then you'll should try and update your program and give the people what they want, and that is to download 96khz.

**Comment by AminurAlam** [comment]
tidal only gives you max 48khz, you'll need an mqa decoding application to get 96khz and for 192khz you'll need mqa supported dac

**Comment by SI0209** [comment]
How can I get an mqa decoding application, which mqa decoding app is good and how can I use it to download a 24bit 96khz song with the streamrip app?Sent from my Galaxy
-------- Original message --------From: AminurAlam ***@***.***> Date: 2021/10/31  17:19  (GMT+02:00) To: nathom/streamrip ***@***.***> Cc: SI0209 ***@***.***>, Author ***@***.***> Subject: Re: [nathom/streamrip] [FEATURE] Tidal supporting and downloading 24bit 96khz audio (Issue #217) 
tidal only gives you max 48khz, you'll need an mqa decoding application to get 96khz and for 192khz you'll need mqa supported dac

**Comment by nathom** [comment]
As AminurAlam said, streamrip fetches the highest quality that TIDAL has, which is mostly 24/48 or 24/44.1. If there is a 24/96 track available, it will download it.

**Comment by drcxd** [comment]
@nathom Hello, I have similar question here. This album: https://tidal.com/browse/album/172577147?u 

If I play it in Tidal app, then the application shows that it is playing 24-bit 96khz FLAC. However, streamrip only downloads 16-bit 44khz FLAC with the quality set to 3. Can you explain why Tidal app can play a higher resolution version?
