### ISSUE TITLE
[FEATURE] Skip albums with 'missing' tracks

### ISSUE THREAD

**Issue by dimqua** [nathom/streamrip#218]
### Is the feature request related to a problem. Please describe it.

Sometimes when you download Qobuz albums, they contain tracks that aren't available for streaming.

### Describe the solution you would like.

It'd be nice to have a possibility to skip downloading of such albums, because it leads to confusion that they are complete when they are not.

**Comment by nathom** [comment]
This would mean checking whether every track is streamable before downloading the album, which would slow down the program to a halt. Most likely not going to implement this.
