### ISSUE TITLE
Fail testing Master Track

### ISSUE THREAD

**Issue by inglesuniversal** [nathom/streamrip#221]
### Is the feature request related to a problem. Please describe it.

[TEST](https://tidal.com/browse/track/100577989)

### Describe the solution you would like.

N/A

### Describe alternatives you've considered.

N/A

**Comment by nathom** [comment]
I'm sorry, I don't understand what the feature request is here.

**Comment by inglesuniversal** [comment]
Oh, I just solved the issue by adding a paid subscription. Thanks
