### ISSUE TITLE
[Quistion] <title>

### ISSUE THREAD

**Issue by Vitz42** [nathom/streamrip#222]
### Describe the bug

How do you download from SoundCloud?

### Command Used

```bash
-
```

### Debug Traceback

```text
-
```

### Config File

```toml
-
```

### Operating System

macOS

### streamrip version

1.7

### Screenshots and recordings

-

**Comment by nathom** [comment]
```
rip url https://soundcloud.com/lilcandypaint/22-feat-bhad-bhabie
```
