### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by darkaeden** [nathom/streamrip#228]
### Is the feature request related to a problem. Please describe it.

I am trying to install via termux in Android but the installation failes.
Command pip3 install streamrip --upgrade
Python and Pip already installed and working.

### Describe the solution you would like.

Possibility to install it in Android, via termux.

**Comment by AminurAlam** [comment]
the command you used and the error you got are different...

**Comment by AminurAlam** [comment]
> What should i use as a command to install streamrip on android? Thanks

read the wiki
https://github.com/nathom/streamrip/wiki

**Comment by darkaeden** [comment]
I checked the wiki and tried the pip3 install streamrip with no avail.
Here pictures of the beginning of the errors reported during commanding on Termux (Android 9).
Looks like there is some incompatibility...

![image](https://user-images.githubusercontent.com/65325147/142518840-1c1e4dc8-d5a4-42a9-a692-dc4c736b8ecd.jpeg)
![image](https://user-images.githubusercontent.com/65325147/142518847-89c95f3a-bfd1-47ad-b6e2-60a1b6303e51.jpeg)
![image](https://user-images.githubusercontent.com/65325147/142518851-3753f540-c4a0-4efe-a055-a46136582c96.jpeg)
![image](https://user-images.githubusercontent.com/65325147/142518858-2f157d1d-ea44-4724-b070-34049ae6ef90.jpeg)

**Comment by AminurAlam** [comment]
@darkaeden install "wheel"
```
pip install wheel
```

**Comment by darkaeden** [comment]
> @darkaeden install "wheel"
> 
> ```
> 
> pip install wheel
> 
> ```
> 
> (also copy/pasted the error or taken screenshot next time instead)

Thanks. By installing wheel, looks like it installed more with pip3 install streamrip.
But still installation fails.

![image](https://user-images.githubusercontent.com/65325147/142571965-bb2d7fef-1b14-4030-829b-6b4e14bd4bfb.jpeg)

![image](https://user-images.githubusercontent.com/65325147/142571976-7ad89c1e-efb2-47ca-9356-0e3320de5653.jpeg)

**Comment by AminurAlam** [comment]
try installing pillow or downgrading to python 3.9

**Comment by AminurAlam** [comment]
have you tried downgrading python?

**Comment by darkaeden** [comment]
> have you tried downgrading python?
> 
> 

Not yet.
Can you pls be so kind to tell me its terminal command? Thanks

**Comment by zjns** [comment]
> > have you tried downgrading python?
> 
> Not yet. Can you pls be so kind to tell me its terminal command? Thanks

It is a Pillow compile bug, not fixed yet, this is a solution from the issues, see https://github.com/python-pillow/Pillow/issues/5801#issuecomment-955181595

**Comment by darkaeden** [comment]
> > > have you tried downgrading python?
> > 
> > 
> > Not yet. Can you pls be so kind to tell me its terminal command? Thanks
> 
> It is a Pillow compile bug, not fixed yet, there is a solution from the issues, see [python-pillow/Pillow#5801 (comment)](https://github.com/python-pillow/Pillow/issues/5801#issuecomment-955181595)

Thanks! It worked now, i could install pillow and stream rip!

**Comment by darkaeden** [comment]
Believe i still need some help.
Trying to download an album from tidal,  by RIP URL ALBUM LINK.
But i receive an error, "Device authorization failed".
Indeed, stream rip did not asked to authorize (link.tidal.com) the connection. 
Thanks a lot for helping.

**Comment by zjns** [comment]
> Believe i still need some help. Trying to download an album from tidal, by RIP URL ALBUM LINK. But i receive an error, "Device authorization failed". Indeed, stream rip did not asked to authorize (link.tidal.com) the connection. Thanks a lot for helping.

see https://github.com/nathom/streamrip/issues/230#issuecomment-974541762, repo need update to fit the change.

**Comment by darkaeden** [comment]
> > Believe i still need some help. Trying to download an album from tidal, by RIP URL ALBUM LINK. But i receive an error, "Device authorization failed". Indeed, stream rip did not asked to authorize (link.tidal.com) the connection. Thanks a lot for helping.
> 
> 
> 
> see https://github.com/nathom/streamrip/issues/230#issuecomment-974541762, repo need update to fit the change.

Clear. Tidal-dl does not work as well, same error. :(
