### ISSUE TITLE
Qobuz login with user id and token

### ISSUE THREAD

**Issue by DJLeleX** [nathom/streamrip#231]
### Is the feature request related to a problem. Please describe it.

Can you please add the login to Qobuz with user id and token?

Thanks

### Describe the solution you would like.

link to @ImAiiR 's guide to login with user id and token: https://github.com/ImAiiR/QobuzDownloaderX/wiki/Logging-In-(The-Alternate-Way)

**Comment by pupto-bismol** [comment]
I actually would really like to see this too! Had the same issue where after coming from qbdlx the login method didn't work with just ID and token

**Comment by CrossyAtom46** [comment]
if this is an closed issue how can i log in with tokens?

**Comment by DJLeleX** [comment]
> if this is an closed issue how can i log in with tokens?

it's closed because it's a feature the dev doesn't want to add.

**Comment by kmajeed** [comment]
@CrossyAtom46 How did you achieve this. can you please share the steps?

**Comment by CrossyAtom46** [comment]
@kmajeed achieving what?

**Comment by quantenzitrone** [comment]
In your `config.toml` in the `[qobuz]` section set `use_auth_token = true`, `email_or_userid` to your id and `password_or_token` to your token.

**Comment by sam9428** [comment]
> In your `config.toml` in the `[qobuz]` section set `use_auth_token = true`, `email_or_userid` to your id and `password_or_token` to your token.

Does anyone know how to get those things to download from quobuz, and configuiring the config file

**Comment by CrossyAtom46** [comment]
They visible on cookies
