### ISSUE TITLE
[BUG] <Login fail Tidal>

### ISSUE THREAD

**Issue by cyberianJE** [nathom/streamrip#233]
### Describe the bug

Today I tried using rip but could not do it with Tidal using the command url

### Command Used

```bash
rip url https://tidal.com/browse/track/203134368
```

### Debug Traceback

```text
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Parsed urls: [('tidal', 'track', 'xxxxxxxxxx')]
DEBUG:streamrip:Searching for {'id': 'xxxxxxxxxx'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
DEBUG:streamrip:{'quality': 3, 'download_videos': True, 'user_id': xxxxxxxxxx, 'country_code': 'xE', 'access_token': 'eyJraWQiOiJ2OU1GbFhqWSIsImFsZyI6IkVTMjU2In0.eyJ0eXBlIjoibzJfYWNjZXNzIiwidWlkIjoxODMwODg2ODIsInNjb3BlIjoid19zdWIgcl91c3Igd191c3IiLCJnVmVyIjowLCJzVmVyIjowLCJjaWQiOjMwMDYsImV4cCI6MTYzNzYzMjU0Niwic2lkIjoiOWZhM2MxMjQtYjFlZi00MzkzLWJhNWYtY2JhZmFkM2EyYzA3IiwiaXNzIjoiaHR0cHM6Ly9hdXRoLnRpZGFsLmNvbS92MSJ9.Oaf0kNlpt-EIB41nuVUid2cVQXcBO48bamOpGTlIge6jQylU3Nh3TMQmJtlwbYMZDlt9cDBoXq6WWbOOfwr-Yg', 'refresh_token': 'eyJraWQiOiJoUzFKYTdVMCIsImFsZyI6IkVTNTEyIn0.eyJ0eXBlIjoibzJfcmVmcmVzaCIsInVpZCI6MTgzMDg4NjgyLCJzY29wZSI6Indfc3ViIHJfdXNyIHdfdXNyIiwiY2lkIjozMDA2LCJzVmVyIjowLCJnVmVyIjowLCJpc3MiOiJodHRwczovL2F1dGgudGlkYWwuY29tL3YxIn0.ANhKkC2RhfQ1r8RTj89J1bP0JRyFTDJbz8e_unuSImmrdTq89J-68qYgReauR_Sg3nayHrV5PZo2TQiCzxOzPoJuAFDvloPrmuU9gNnt5XChHXS8o_An26mYSWpOu9TKdqfUP85bLwJuuV-DH3QU_7fqi_C6fhubdhNQ-wq9zEWepsRz', 'token_expiry': 1637632546.2879903}
DEBUG:streamrip:Logging in with access token

  Stack trace:

  12  AppData\Local\Programs\Python\Python39\lib\site-packages\cleo\application.py:314 in run
       312│
       313│             try:
     → 314│                 exit_code = self._run(io)
       315│             except Exception as e:
       316│                 if not self._catch_exceptions:

  11  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\cli.py:604 in _run
       602│             logger.addHandler(fh)
       603│
     → 604│         super()._run(io)
       605│
       606│     def create_io(self, input=None, output=None, error_output=None):

  10  AppData\Local\Programs\Python\Python39\lib\site-packages\cleo\application.py:409 in _run
       407│                 io.set_input(ArgvInput(argv))
       408│
     → 409│         exit_code = self._run_command(command, io)
       410│         self._running_command = None
       411│

   9  AppData\Local\Programs\Python\Python39\lib\site-packages\cleo\application.py:416 in _run_command
       414│     def _run_command(self, command: Command, io: IO) -> int:
       415│         if self._event_dispatcher is None:
     → 416│             return command.run(io)
       417│
       418│         # Bind before the console.command event,

   8  AppData\Local\Programs\Python\Python39\lib\site-packages\cleo\commands\base_command.py:118 in run
       116│         io.input.validate()
       117│
     → 118│         status_code = self.execute(io)
       119│
       120│         if status_code is None:

   7  AppData\Local\Programs\Python\Python39\lib\site-packages\cleo\commands\command.py:85 in execute
        83│
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   6  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\cli.py:84 in handle
        82│
        83│         if urls:
     →  84│             core.handle_urls(";".join(urls))
        85│
        86│         if len(core) > 0:

   5  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\core.py:186 in handle_urls
       184│                 continue
       185│
     → 186│             self.handle_item(source, url_type, item_id)
       187│
       188│     def handle_item(self, source: str, media_type: str, item_id: str):

   4  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\core.py:198 in handle_item
       196│         :type item_id: str
       197│         """
     → 198│         client = self.get_client(source)
       199│
       200│         if media_type not in MEDIA_TYPES:

   3  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\core.py:360 in get_client
       358│         if not client.logged_in:
       359│             try:
     → 360│                 self.login(client)
       361│             except DeezloaderFallback:
       362│                 client = self.clients["deezloader"]

   2  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\core.py:385 in login
       383│         while True:
       384│             try:
     → 385│                 client.login(**creds)
       386│                 break
       387│             except AuthenticationError:

   1  AppData\Local\Programs\Python\Python39\lib\site-packages\streamrip\clients.py:751 in login
        749│             else:
        750│                 logger.debug("Logging in with access token")
     →  751│                 self._login_by_access_token(access_token, user_id)
        752│         else:
        753│             logger.debug("Logging in as a new user")

  Exception

  Login failed {'status': 401, 'subStatus': 6001, 'userMessage': 'User does not have a valid session'}

  at AppData\Local\Programs\Python\Python39\lib\site-packages\streamrip\clients.py:968 in _login_by_access_token
       964│         resp = self.session.get(
       965│             "https://api.tidal.com/v1/sessions", headers=headers
       966│         ).json()
       967│         if resp.get("status", 200) != 200:
    →  968│             raise Exception(f"Login failed {resp}")
       969│
       970│         if str(resp.get("userId")) != str(user_id):
       971│             raise Exception(f"User id mismatch {resp['userId']} v {user_id}")
       972│

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\usuario 1\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false
```

### Operating System

windows 10

### streamrip version

1.7

### Additional context

The last time It was fine was just 5 days ago.

**Comment by Rekulous** [comment]
As of now, TIDAL Login & Ripping is broken due to a new update.

You're gonna have to wait.

**Comment by 89z** [comment]
If someone can provide credentials, I can work on this. Just run the following command and comment back with the output:

~~~
echo USER:PASS | age -a -r age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77hy6
~~~

https://github.com/FiloSottile/age

**Comment by uwulily** [comment]
#232

**Comment by elvetemedve** [comment]
Hi @89z,

I can offer an account for you: 
```
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQXZTVFl6K0RuMlhwUUt1
aVBjaGtsWDZONG1Ja0FjYlF6Vm1rakNMeHlzCnh1cU93ekNxcmRUL2xNQVpVOXJ5
WTlwWC9yOWw1ZC8yejlhaEVrQnZ3eVEKLS0tIGtTVDZ4QmZ4VlRodElWUGZRY3p6
aTVORVBqUTFZT2c5azdlVUluaFA1bEEK32BRGzh6aYIhwZJfTQW3wjUyRkAmcE9U
I+iJ1GUeR1MZOKzPezd1fuTIeMM9fxxCKQL8tqQ4l7493eQYRP5n5yVuNMzwj+Nc
-----END AGE ENCRYPTED FILE-----
```

**Comment by 89z** [comment]
@elvetemedve thanks that works, but @uwulily PR seems to be a good, simple fix. If thats not the case, then I can continue work on this.

**Comment by darkaeden** [comment]
> @elvetemedve thanks that works, but @uwulily PR seems to be a good, simple fix. If thats not the case, then I can continue work on this.

Can you please let me know / redirect to the simple fix mentioned? Thanks a lot

**Comment by Wim1975** [comment]
Hi, With the fix, downloads are working, but I'm no longer seeing 24/44 or 24/48 mqas but mqas that are downsampled to 16/44 where the mqa signal is destroyed so they can no longer unfold and look like 16/44 pcms (hifi). Same issue as tidal-dl.

(Tidal calls this "cd-quality" but clearly these are not redbooks but mangled mqas.
If no longer able to download mqas, I'm ditching Tidal for this same reason)

**Comment by 89z** [comment]
what the hell is "mqa"?

**Comment by elvetemedve** [comment]
> what the hell is "mqa"?

LTDR
A new audio format which meant to be superior to existing audio formats in quality, but in practice it's questionable.

MQA is explored in detain in this video:
https://www.youtube.com/watch?v=pRjsu9-Vznc

**Comment by Wim1975** [comment]
> what the hell is "mqa"?

On tidal all albums that are labeled "master" are mqas, Mqa is a lossy compression, it's like mp3 v2.0.

If you'd happen to download those "master" file in their "hifi" tier, you'd expect to get a redbook version, because they promiss to give you "lossless cd quality" but no...
 
In stead, you get those same mqas, but this time they are down sampled to 16/44 
This way you see "PCM 16/44" on your dac - because Tidal+MQA wants you to believe you are listening to a "lossless cd quality" recording - but actually you are just listening to a crippled mqa. 

For this reason some people think mqa sounds better than cd quality, as they don't realize it's just mqa sounding better then crippled mqa. :-)

The original redbooks can be found on Qobuz if you want an honest comparison between tidals interpretation of cd quality and real lossless quality.

**Comment by 89z** [comment]
> The original redbooks can be found on Qobuz if you want an honest comparison between tidals interpretation of cd quality and real lossless quality.

If youre interested in lossless quality, then why do you even care to get mqa? It seems even in the best circumstance, you getting a lossy product.

**Comment by Wim1975** [comment]
> > The original redbooks can be found on Qobuz if you want an honest comparison between tidals interpretation of cd quality and real lossless quality.
> 
> If youre interested in lossless quality, then why do you even care to get mqa? It seems even in the best circumstance, you getting a lossy product.

I was talking about their interpretation of "cd quality" which seem to be still those same mqas, only crippled ones.
If I can choose between a 16/44 and a 15/44 + 1bits of mqa data then it's clear the 16/44 is better.

Besides, why turn 44.1ks into mqa when there's nothing to fold anyway? (Nyquist : no frequencies > 22k were recorded)
The bit is only there to show "MQA" on the dac + a number + a dot + to select a short filter that blurs the frequencies.

**Comment by 89z** [comment]
https://github.com/nathom/streamrip/issues/236

**Comment by cyberianJE** [comment]
Could you let me know what the fox is? I just saw something about constants.py.

**Comment by Wim1975** [comment]
> Could you let me know what the fox is? I just saw something about constants.py.

https://github.com/nathom/streamrip/pull/232/files

**Comment by cyberianJE** [comment]
I got a message saying that tidal is downloads are back up, although they are now restricted to quietly =2. 

Problem is I still get an error when I use the command "rip url + tidal address"
How can I get back to downloading from tidal? 
Any help?

**Comment by Rekulous** [comment]
> I got a message saying that tidal downloads are back up, although they are now restricted to quality =2.
> 
> Problem is I still get an error when I use the command "rip url + tidal address" How can I get back to downloading from tidal? Any help?

Run `pip3 / pip install streamrip --upgrade` and you're set!

**Comment by cyberianJE** [comment]
> > I got a message saying that tidal downloads are back up, although they are now restricted to quality =2.
> > Problem is I still get an error when I use the command "rip url + tidal address" How can I get back to downloading from tidal? Any help?
> 
> Run `pip3 / pip install streamrip --upgrade` and you're set!

Unfortunately, after running that command I get this error message:

Exception

  Refresh failed

  at AppData\Local\Programs\Python\Python39\lib\site-packages\streamrip\clients.py:947 in _refresh_access_token
       943│             (TIDAL_CLIENT_INFO["id"], TIDAL_CLIENT_INFO["secret"]),
       944│         )
       945│
       946│         if resp.get("status", 200) != 200:
    →  947│             raise Exception("Refresh failed")
       948│
       949│         self.user_id = resp["user"]["userId"]
       950│         self.country_code = resp["user"]["countryCode"]
       951│         self.access_token = resp["access_token"]

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
