### ISSUE TITLE
[DOCUMENTATION] login() method

### ISSUE THREAD

**Issue by Paranoid-Pirate** [nathom/streamrip#235]
### Is the feature request related to a problem. Please describe it.

In the wiki for the python library it lists you can use the login() method for qobuz and tidal, however it doesn't list usage of the login method and there is no library documentation, and just doing yourClient.login() gives you the error of `KeyError: 'email'. At` least none obvious to me from the github itself or any google search.

### Describe the solution you would like.

Generic documentation on methods, or a link to where it is documented.

### Describe alternatives you've considered.

I've tried putting email and password info into config.toml to get the same `KeyError: 'email'` text either way. Inputting it into the login() method itself also changes nothing.

**Comment by AminurAlam** [comment]
just use this command to log in
for qobuz
```
rip config --qobuz
```
for tidal
```
rip config --tidal
```
i hope this solves the problem

**Comment by Paranoid-Pirate** [comment]
I still get the same error when calling `client.login()` after doing the command `rip config --qobuz` and putting in the correct info

**Comment by AminurAlam** [comment]
maybe this is because qobuz made some changes to the api, wait for a fix
