### ISSUE TITLE
[BUG] Installation error

### ISSUE THREAD

**Issue by What-Zit-Tooya** [nathom/streamrip#251]
### Describe the bug

Can not install streamrip

### Command Used

```bash
pip3 install streamrip --upgrade

pip3 install streamrip
```

### Debug Traceback

```text
LOG: [Error.log](https://github.com/nathom/streamrip/files/7709047/Error.log)
```

### Config File

```toml
N/A
```

### Operating System

Windows 10 x64

### streamrip version

N/A

**Comment by CanadianBaconBoi** [comment]
Well, it's not a bug if the error log is indeed https://github.com/nathom/streamrip/files/7709047/Error.log

`Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

**Comment by What-Zit-Tooya** [comment]
> 

Already installed this https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
As required on installation instruction, but still give me error message above

**Comment by greenzwiz** [comment]
Install [Microsoft Build Tools for Visual Studio.](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022)

Select: Workloads → Desktop development with C++, then for Individual Components, select only:

1. Windows SDK
2. C++ x64/x86 build tools

Restart your computer. Should work after that.

**Comment by What-Zit-Tooya** [comment]
> 

![2](https://user-images.githubusercontent.com/9832875/150769935-9c78218a-6e33-4514-a1c8-ae38b24dfa70.png)
It required almost 5 GB of size.
I just want install this script

**Comment by CanadianBaconBoi** [comment]
@What-Zit-Tooya Go to this link https://visualstudio.microsoft.com/visual-cpp-build-tools/ , download the build tools from here. Under the top tab "Individual Components" search for "MSVC v142 - VS 2019 C++ x64/x86 build tools (Latest)". Just install this along with the default selected MSBuild Tools. Total size is about 2 gb.

**Comment by aberfan** [comment]
I have this same issue. So to run this python script on windows requires installing 2gb of Microsoft stuff? And that's after having to deal with installing a version over 3.9, which of course doesn't work on Windows 7 but thankfully some kind soul forked one.  Maybe it should be noted it's unsupported more or less on Windows??

" error: Microsoft Visual C++ 14.0 or greater is required."
