### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by Aridlvory** [nathom/streamrip#256]
After installing streamrip using
`pip3 install streamrip`
It shows python error after typing `rip`
![Screenshot_20211222-135452_Termux.jpg](https://user-images.githubusercontent.com/78092537/147060822-c14dac29-7650-45fa-be18-fe8f3d747f14.jpg)

**Comment by 89z** [comment]
Could you specify what site you are interested in?

**Comment by nathom** [comment]
You need to update streamrip to the latest version.
