### ISSUE TITLE
[BUG] Error in handling of failed booklet downloads

### ISSUE THREAD

**Issue by crankedguy** [nathom/streamrip#257]
### Describe the bug

Hi, you have erronous code if booklet downloads failed. You put the media type "booklet" into the sqlite db.
But when calling the repair command you assert it against a list that does not contain that media type.

### Command Used

```bash
rip repair
```

### Debug Traceback

```text
`MEDIA_TYPES = {"track", "album", "artist", "label", "playlist", "video"}`


AssertionError

  booklet

  at ~/.local/lib/python3.10/site-packages/rip/core.py:204 in handle_item
      200│         if media_type not in MEDIA_TYPES:
      201│             if "playlist" in media_type:  # for SoundCloud
      202│                 media_type = "playlist"
      203│ 
    → 204│         assert media_type in MEDIA_TYPES, media_type
      205│         item = MEDIA_CLASS[media_type](client=client, id=item_id)
      206│         self.append(item)
      207│ 
      208│     def _get_download_args(self) -> dict:

```
```


### Config File

```toml
Not applicable in this case
```

### Operating System

Linux

### streamrip version

1.8

**Comment by crankedguy** [comment]
In order for that i might generally propose to add some file information to the sqlite databases, at least the error db. It would make it much easier to see which files had problems.

**Comment by Wim1975** [comment]
I concur booklets can cause streamrip to crash. (Have it disabled by default for now)
