### ISSUE TITLE
Feature request: If possible skip duplicates and keep highest bitrate  

### ISSUE THREAD

**Issue by Gamer4Life2020** [nathom/streamrip#26]
Thanks for this first off, I have been using other downloaders so this AIO is great.
Not sure if possible but it would be nice to only download the highest bitrate if an artist the same multiple times in various bitrates.
As to avoid duplicates or overwriting other tracks and having a mixed bitrate album. I don't mine doing one at a time or a list if need be but would love the artist download without duplicates or mixed media.

Thanks

**Comment by Gamer4Life2020** [comment]
Also, I can login to Qobuz but errors out can't DL anything. Haven't tried Deezer yet or Tidal as I prefer Qubuz over Tidal.
Is there a log file or if needed would you like screen shots?

**Comment by nathom** [comment]
Can you please split up the bugs you mentioned into seperate issues? Also please include whatever is shown on the screen when the program errors out. Thanks.
