### ISSUE TITLE
[BUG] Unable to install, failed on compiling

### ISSUE THREAD

**Issue by mooock** [nathom/streamrip#262]
### Describe the bug

When trying to install, it fails to compile, already from the start missing dependencies required made it fail

Wheel was missing
cchardet was trying to run in legacy mode.

installed both with pip to make the installer continue, but have now ended up with the error from the screenshot

### Command Used

```bash
pip3 install streamrip --upgrade
```

### Debug Traceback

```text
didnt install so i cannot run the command
```

### Config File

```toml
didnt install so i cannot run the command
```

### Operating System

Server 2012R2

### streamrip version

streamrip v1.8

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/1118931/147614665-0c7b6196-5b3e-4d3e-ba25-9ef4615799c4.png)

### Additional context

it was a clean installation of python 3.10 and also visual build c++ dependencies.

**Comment by 89z** [comment]
Could you specify what site you are interested in?

**Comment by mooock** [comment]
> e

i didn't even come to the part of using the software, this was just for installing streamrip, but my intention was to try out tidal

**Comment by 89z** [comment]
I am working on a Tidal downloader, would you mind providing an example URL?

**Comment by mooock** [comment]
> I am working on a Tidal downloader, would you mind providing an example URL?

i could not come to the part to where i need to download. i was already stopped on the installation part, where the error comes up

pip3 install streamrip --upgrade

**Comment by Peterak100** [comment]
I just had the exact same issue so wasn't able to install

**Comment by ezxpro** [comment]
Same here. Apparently the installation script has done something wrong in regards to cchardet.

You can install chardet just fine using `pip3 install chardet`, but somehow it seems there's a setup.py file here that is messed up.

**Comment by jaylex32** [comment]
everytime I type rip in terminal it gives me a python error, I have use streamrip before but now for some reason I get this error no matter what I do, any ideas?
