### ISSUE TITLE
[FEATURE] Add metadata setting to remove (Explicit) tag from songs

### ISSUE THREAD

**Issue by Rekulous** [nathom/streamrip#263]
### Is the feature request related to a problem. Please describe it.

No, the feature request is not related to a problem.

### Describe the solution you would like.

I would like StreamRip to add a metadata setting to make music that is ripped to not contain the (Explicit) tag shown in track names.

Whenever a song or album that is ripped is explicit, StreamRip will add an (Explicit) tag at the end of a track name and I don't really like this because I prefer it when the track names don't have the (Explicit) tag.

Whenever I scrobble songs that have the (Explicit) tag on them in Last,fm using foobar2000, it doesn't show the actual song, just the one with the (Explicit) tag on it and that messes up my scrobbles for me.

There shouldn't be any drawbacks to this feature since it's just a metadata setting and can be enabled or disabled.

### Describe alternatives you've considered.

An alternative solution to fix or remove the (Explicit) tag is to manually edit the metadata for the tracks myself or by using a Bulk Rename Tool, but sometimes it gets really repetitive and wastes a lot of time for me. Having a metadata setting added would save much more time and make things more simple for users.

**Comment by idillionaire** [comment]
I agree. I realised also that if one track is tagged explicit on a album while the other songs aren’t, streamrip will tag all the tracks as explicit, I think this is a bug

**Comment by Rekulous** [comment]
> I agree. I realised also that if one track is tagged explicit on a album while the other songs aren’t, streamrip will tag all the tracks as explicit, I think this is a bug

Yes that's true. Happened to me many times.

**Comment by nathom** [comment]
This has been implemented in the dev branch. It will be merged in the next version.

**Comment by Rekulous** [comment]
> This has been implemented in the dev branch. It will be merged in the next version.

Very cool
