### ISSUE TITLE
[BUG] Unable to install 

### ISSUE THREAD

**Issue by s0902rx** [nathom/streamrip#269]
### Describe the bug

Same error as others during install. 

### Command Used

```bash
pip install streamrip
```

### Debug Traceback

```text
/
```

### Config File

```toml
/
```

### Operating System

Windows 10 Pro 

### streamrip version

/

### Screenshots and recordings

https://user-images.githubusercontent.com/79232286/149224885-97dfd641-4c68-4384-b530-41fab73d26ea.mp4

**Comment by nathom** [comment]
As the error message says, you need "Microsoft C++ Build Tools"
<img width="549" alt="image" src="https://user-images.githubusercontent.com/74019033/149670004-03846a69-17fc-4aaf-91a1-0d3d5c160ffb.png">
