### ISSUE TITLE
Feature Request: Library Sync

### ISSUE THREAD

**Issue by tretneo** [nathom/streamrip#27]
I'd love to see a feature that looks at your favorited Albums/Tracks on Qobuz and/or Tidal, compares those to the streamrip database (already downloaded) and downloads the delta. This would allow you to run streamrip periodically (nightly, for example) to update your local library w/ any new favorites added since the previous run.

**Comment by nathom** [comment]
This should already be possible by creating a public playlist and adding music to it. Then, when you run `rip -u linktoplaylist.com`, the already downloaded tracks will be skipped as their IDs have been logged.

I will look into adding access to user favorites. Thanks for the suggestion.

**Comment by tretneo** [comment]
I'll give that approach a try. Thanks for the tip!

**Comment by nathom** [comment]
Moved to #42
