### ISSUE TITLE
[FEATURE] resume 

### ISSUE THREAD

**Issue by CtheG** [nathom/streamrip#276]
### Is the feature request related to a problem. Please describe it.

When tidal-downloading an url/album and the download gets interrupted, it' still saved into the database.
Even if only 4 out of 10 tracks finished.
When trying to restart/repair it says Track 1.FLAC already exists - skipping.
It does not try for the missing files.

If a solution inside the program exists to solve this, I cannot see how it's supposed to.
The problem seems to not be de db-entry, but the existence of a file which corresponds to the url (of an artist/album/..)

### Describe the solution you would like.

Example:
When using a link for 1 artist who has 3 albums.
Album 1 finishes
and of album 2 only 3 out of 10 songs get downloaded.
Instead of skipping the whole artist/album2(+3), the program should check whether there are tracks of an album missing or even more albums with tracks.

### Describe alternatives you've considered.

retry, retry, repair, ignore db, retry

**Comment by nathom** [comment]
Run `rip db --list failed-downloads` to see if the failed tracks have been logged. If so, you should be able to run `rip repair` to re-download them.

**Comment by dajhorn** [comment]
This glitch persists into the current release with the Deezer backend.  Streamrip-1.9.5 fails on the second invocation of any failed or interrupted download with "\<file\> already exists. Skipping."

Tickets #150  and #342 seem related to this bug.  `rip db --list failed-downloads` returns empty.  Earlier suggestions like `repeats = true` and `rip repair` don't fix it.
