### ISSUE TITLE
Tracks with "#" in the title not available for download from Deezer

### ISSUE THREAD

**Issue by bern-dog** [nathom/streamrip#28]
Might be related to the way tracks with question marks can't be downloaded, but just wanted to bring this to your attention in case it's fixable. Thanks again and appreciate all the quick updates and fixes!

**Comment by nathom** [comment]
Can you give an example link?

**Comment by bern-dog** [comment]
Sure, the first track in this album. I couldn't get it to work: deezer.com/us/album/130305912

**Comment by nathom** [comment]
It seems to be a server side issue. Unfortunately, I can't do anything about it.
