### ISSUE TITLE
[BUG]  when Config file corrupted  not able to start anymore

### ISSUE THREAD

**Issue by daxiawj** [nathom/streamrip#295]
### Describe the bug

I use rip config --open to modify the file, but I may modified it wrongly. so after that it broke. with 

"Invalid character M in string at line 3 col 13 "

question is: how can i find the config file and rm it? 

cannot find streamrip dir it in c:\users\user\appdata\roaming\

### Command Used

```bash
rip config --reset
```

### Debug Traceback

```text
ignored
```

### Config File

```toml
cannot find streamrip dir it in c:\users\user\appdata\roaming\
```

### Operating System

windows

### streamrip version

1.9.2

**Comment by nathom** [comment]
You can open it with `rip config --open`

**Comment by daxiawj** [comment]
> You can open it with `rip config --open`

The problem is. this command also does not work, because of the corrupted config file.
