### ISSUE TITLE
zsh: command not found: rip

### ISSUE THREAD

**Issue by caxcs** [nathom/streamrip#310]
### Describe the bug

zsh: command not found: rip

### Command Used

```bash
rip
```

### Debug Traceback

```text
None
```

### Config File

```toml
None
```

### Operating System

macOS

### streamrip version

new

### Screenshots and recordings

<img width="1180" alt="Snipaste_2022-03-09_13-40-43" src="https://user-images.githubusercontent.com/101239933/157379848-d48e2229-c258-42bf-8481-acda02cd2cb4.png">

### Additional context

I've successfully installed python and streamrip, but I'm getting this error typing rip, I think it should be added to path？ but I don't know what to do, sorry I'm a code noob, any help would be greatly appreciated, thanks!

**Comment by reaitten** [comment]
**rip** is a python module so it won't be in __/opt/rip/bin__. 
running `python3 -m rip` should work

**Comment by caxcs** [comment]
reaitten Thank you very much! Resolved
