### ISSUE TITLE
[FEATURE] Force a language on metadata tagging

### ISSUE THREAD

**Issue by drpoutine** [nathom/streamrip#316]
### Is the feature request related to a problem. Please describe it.

Qobuz ripping uses the language in the account setting. Can't use english by default. 

### Describe the solution you would like.

Force a way to use english metadata only on ripping regardless of language set in User Interface setting inside qobuz web.

### Describe alternatives you've considered.

requires language switching in https://play.qobuz.com/user/settings

**Comment by KevinJamesSmirking** [comment]
I would need this as well.
