### ISSUE TITLE
[FEATURE] Skipping/overwriting already downloaded tracks

### ISSUE THREAD

**Issue by tacohitbox** [nathom/streamrip#329]
### Is the feature request related to a problem. Please describe it.

Specifically, I have only caught it on the artist Weezer on Tidal but some artists have dupes. When downloading the whole artist, it tries download a dupe of an album. And, as a result, fails the download.

![image](https://user-images.githubusercontent.com/87399016/167766074-7f7fa03f-69d7-4a8d-8836-cacdc9fbbb9d.png)

### Describe the solution you would like.

I'd like to have an option to skip already downloaded items, this would make updating artists much easier rather than searching by album. Like appending ``--skip-duplicates`` and ``--overwrite-duplicates`` to a request. 

Only drawback being which should be default? Skipping dupes, overwriting dupes, or stopping like it does now.

### Describe alternatives you've considered.

I tried looking around for issues similar to mine with no luck :(

**Comment by nathom** [comment]
You can set `repeats = true` in the `filters` section of the config file.

```toml
[filters]
# Picks the highest quality out of albums with identical titles.
repeats = true
```

**Comment by tacohitbox** [comment]
Alright then, thanks for pointing this out.
