### ISSUE TITLE
enhancement: Solve duplicates or overwriting tracks 

### ISSUE THREAD

**Issue by Gamer4Life2020** [nathom/streamrip#33]
If possible could you add to the folder naming like [E] for explicit so we know if duplicate albums what is what without looking at the cover or listening to it.

Also, you could add like the barcode, isrc, upc codes to the tags and folder [56854065] to separate albums and keep it from overwriting tracks. 
<img width="721" alt="QO-DL Tags" src="https://user-images.githubusercontent.com/36717721/113915046-e0170300-97a3-11eb-82be-52c29c4ac7f1.PNG">

**Comment by nathom** [comment]
Added in 0.3.2
