### ISSUE TITLE
Stream rip is saying track already exists. Skipping. When downloading full artist link from tidal

### ISSUE THREAD

**Issue by Aeiron2** [nathom/streamrip#358]
### Describe the bug

Basically a new artist Ive never downloaded before 
it's saying usually in the first album that a track already exists and its skipping it therefore halting the whole process. Not even downloading the next album.
I tried to override with the -ignore -db command and delete the existing file but it just keeps screwing up and aborting the whole catalog. 
rip db --list failed-downloads and rip repair do nothing
I've read people with similar issues here and I'm wondering when will this get addressed?

### Command Used

```bash
rip url --max-quality 1 -- https://listen.tidal.com/artist/661
rip url --ignore-db --max-quality 1 -- https://listen.tidal.com/artist/661
```

### Debug Traceback

```text
"D:\StreamripDownloads\Jennifer Lopez\Jennifer Lopez, Maluma - Marry Me (Original Motion Picture Soundtrack) (2022) [AAC] [UnknownB-UnknownkHz]\01. Coolidge Crew - Here Comes the Bride.m4a" already exists. Skipping.
```

### Config File

```toml
d:/streamripdownloads
```

### Operating System

windows 10 x64 bit

### streamrip version

Rip (version 1.9.5

### Additional context

https://github.com/nathom/streamrip/issues/342
https://github.com/nathom/streamrip/issues/276

**Comment by jv3o3** [comment]
> ### Describe the bug
> Basically a new artist Ive never downloaded before it's saying usually in the first album that a track already exists and its skipping it therefore halting the whole process. Not even downloading the next album. I tried to override with the -ignore -db command and delete the existing file but it just keeps screwing up and aborting the whole catalog. rip db --list failed-downloads and rip repair do nothing I've read people with similar issues here and I'm wondering when will this get addressed?
> 
> ### Command Used
> ```shell
> rip url --max-quality 1 -- https://listen.tidal.com/artist/661
> rip url --ignore-db --max-quality 1 -- https://listen.tidal.com/artist/661
> ```
> 
> ### Debug Traceback
> ```
> "D:\StreamripDownloads\Jennifer Lopez\Jennifer Lopez, Maluma - Marry Me (Original Motion Picture Soundtrack) (2022) [AAC] [UnknownB-UnknownkHz]\01. Coolidge Crew - Here Comes the Bride.m4a" already exists. Skipping.
> ```
> 
> ### Config File
> ```toml
> d:/streamripdownloads
> ```
> 
> ### Operating System
> windows 10 x64 bit
> 
> ### streamrip version
> Rip (version 1.9.5
> 
> ### Screenshots and recordings
> _No response_
> 
> ### Additional context
> #342 #276

Did you figure out a solution to this issue?

**Comment by Aeiron2** [comment]
No, I just manually download the albums from the artist if I get this error

**Comment by nathom** [comment]
This shouldn't happen on v2

**Comment by TheUltimateC0der** [comment]
Still happens on 2.0.4
