### ISSUE TITLE
[FEATURE] <title>https://www.qobuz.com/us-en/album/nothing-left-to-love-counterparts/ib572tem87lsc

### ISSUE THREAD

**Issue by aldobryan** [nathom/streamrip#361]
### Is the feature request related to a problem. Please describe it.

yes

### Describe the solution you would like.

syes

### Describe alternatives you've considered.

y

**Comment by Fijxu** [comment]
You are a big dumbass

**Comment by reaitten** [comment]
society

**Comment by Fijxu** [comment]
omg this shit bot that nobody wants
