### ISSUE TITLE
[FEATURE] Set API rate limit

### ISSUE THREAD

**Issue by ryfont** [nathom/streamrip#366]
### Is the feature request related to a problem. Please describe it.

API Call limits with country code followed by =100.

### Describe the solution you would like.

It would be great to set a slower download rate so that you do not get rate limited by Tidal and miss most of the songs of an artist. This causes the need to run the program multiple times to make sure you get all the songs one has. No matter what country is selected, it always gives a 10-30 ish second cooldown after rapidly downloading 100 songs. With this implementation bulk downloading would be way easier. (No need to run the same command thrice) 

An alternative better solution would be to halt all downloads as soon as this limit has been reached and to automatically resume after the allotted cooldown period has expired. 

### Describe alternatives you've considered.

Manually throttling the allowed bandwidth the the application or system OS.

**Comment by JDTCC** [comment]
Hi, is there any update on this?

**Comment by nathom** [comment]
Sorry I missed this. I will try to implement this by next week. Thanks for the suggestion.

**Comment by nathom** [comment]
I have a working implementation on the dev branch, but I cannot test for your use case since I don't have the same issue. Can you install the dev version with

```
pip uninstall streamrip && pip install https://github.com/nathom/streamrip/archive/dev.zip
```

and let me know whether it fixes the issue? If you have issues with the config file try resetting it with `rip config --reset`.

**Comment by JDTCC** [comment]
With the dev test branch I have configured the limit to some test value and everything appears normal. I get this unrelated error now with all commands; 

C:\Users\xxx\xxxxxxx\xxxxx\xxxx>rip url https://tidal.com/browse/artist/xxxxxxx

  AttributeError

  'NoneType' object has no attribute 'json'

  at ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamrip\clients.py:1103 in _api_post
      1099│         :param url:
      1100│         :param data:
      1101│         :param auth:
      1102│         """
    → 1103│         return self.session.post(url, data=data, auth=auth, verify=False).json()
      1104│
      1105│
      1106│ class SoundCloudClient(Client):
      1107│     """SoundCloudClient."""

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
