### ISSUE TITLE
[FEATURE] Max Folder Length Parameter

### ISSUE THREAD

**Issue by prescient** [nathom/streamrip#370]
### Is the feature request related to a problem. Please describe it.

Downloading classical albums often fails due to what I believe are album titles that are too long. I would suggest an option to set a max folder name length in characters and truncate folders which exceed the max length.

### Describe the solution you would like.

Config parameter that allows a user to set the max folder name length in characters.

### Describe alternatives you've considered.

Set folder name to artist and year.

**Comment by Wim1975** [comment]
Yes this is an annoying one. f.i. I use :
folder_format = "{albumartist}\\{title} - [{year}] - {bit_depth}-{sampling_rate} - #{id}"

On Qobuz an album title (field {title}) can be very long when additional info is added (ex. Live at Steakhouse Greasy Paws - Houston - Texas, September 14th 1968, 1996 - Remaster).

Now when pathnames get too long, they are struncated, but in my case, the id field gets truncated, or even the sample rate field, etc..

A better way would be to have an additional field like
{titlelen} = 30
and whenever {title} is longer, then title should be truncated BEFORE the complete pathname is constructed,
that way the important fields like id, sampling_rate, bit_depth and year don't get mangled.
