### ISSUE TITLE
[FEATURE] Switch to charset_normalizer to support python 3.10+

### ISSUE THREAD

**Issue by GUUser91** [nathom/streamrip#377]
### Is the feature request related to a problem. Please describe it.

I'm unable to install streamrip because cchardet can't be installed. cchardet can't be installed because it's not supported in python 3.10 or newer. There is no update for cchardet because it has been abandoned. I'm using the latest version of python on the android app termux. I get a "SSL module is not available in python" error message if I use a downgraded version of python in termux.

### Describe the solution you would like.

Switches streamrip to use charset_normalizer instead of cchardet.

**Comment by fromdetroit7** [comment]
install cython before cchardet

**Comment by GUUser91** [comment]
@fromdetroit7
Yep, that did it. Thank you, you're very helpful.
