### ISSUE TITLE
[BUG] can't get it install or running under windows 11

### ISSUE THREAD

**Issue by aniel300** [nathom/streamrip#384]
### Describe the bug

can't get it install or running under windows 11

### Command Used

```bash
https://github.com/nathom/streamrip
https://github.com/nathom/streamrip/wiki#detailed-installation-instructions
```

### Debug Traceback

```text
n/a
```

### Config File

```toml
n/a
```

### Operating System

windows 11

### streamrip version

n/a

### Screenshots and recordings

`C:\Users\windows7\Desktop\streamrip-main\New folder>pip3 install streamrip
Collecting streamrip
  Using cached streamrip-1.9.5-py3-none-any.whl (84 kB)
Collecting Pillow<10.0.0,>=9.0.0
  Using cached Pillow-9.4.0-cp311-cp311-win_amd64.whl (2.5 MB)
Collecting aiodns<4.0.0,>=3.0.0
  Using cached aiodns-3.0.0-py3-none-any.whl (5.0 kB)
Collecting aiofiles<0.8.0,>=0.7.0
  Using cached aiofiles-0.7.0-py3-none-any.whl (13 kB)
Collecting aiohttp<4.0.0,>=3.7.4
  Using cached aiohttp-3.8.3-cp311-cp311-win_amd64.whl (317 kB)
Collecting appdirs<2.0.0,>=1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting cchardet<3.0.0,>=2.1.7
  Using cached cchardet-2.1.7.tar.gz (653 kB)
  Preparing metadata (setup.py) ... done
Collecting cleo==1.0.0a4
  Using cached cleo-1.0.0a4-py3-none-any.whl (77 kB)
Collecting click<9.0.0,>=8.0.1
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting deezer-py==1.3.6
  Using cached deezer_py-1.3.6-py3-none-any.whl (25 kB)
Collecting m3u8<0.10.0,>=0.9.0
  Using cached m3u8-0.9.0-py3-none-any.whl (22 kB)
Collecting mutagen<2.0.0,>=1.45.1
  Using cached mutagen-1.46.0-py3-none-any.whl (193 kB)
Collecting pathvalidate<3.0.0,>=2.4.1
  Using cached pathvalidate-2.5.2-py3-none-any.whl (20 kB)
Collecting pycryptodomex<4.0.0,>=3.10.1
  Using cached pycryptodomex-3.16.0-cp35-abi3-win_amd64.whl (1.7 MB)
Collecting requests<3.0.0,>=2.25.1
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting tomlkit<0.8.0,>=0.7.2
  Using cached tomlkit-0.7.2-py2.py3-none-any.whl (32 kB)
Collecting tqdm<5.0.0,>=4.61.1
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Requirement already satisfied: windows-curses<3.0.0,>=2.2.0 in c:\users\windows7\appdata\local\programs\python\python311\lib\site-packages (from streamrip) (2.3.1)
Collecting crashtest<0.4.0,>=0.3.1
  Using cached crashtest-0.3.1-py3-none-any.whl (7.0 kB)
Requirement already satisfied: pylev<2.0.0,>=1.3.0 in c:\users\windows7\appdata\local\programs\python\python311\lib\site-packages (from cleo==1.0.0a4->streamrip) (1.4.0)
Collecting pycares>=4.0.0
  Using cached pycares-4.3.0-cp311-cp311-win_amd64.whl (76 kB)
Collecting attrs>=17.3.0
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Collecting charset-normalizer<3.0,>=2.0
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.4-cp311-cp311-win_amd64.whl (28 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.8.2-cp311-cp311-win_amd64.whl (55 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.3-cp311-cp311-win_amd64.whl (32 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting iso8601
  Using cached iso8601-1.1.0-py3-none-any.whl (9.9 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting cffi>=1.5.0
  Using cached cffi-1.15.1-cp311-cp311-win_amd64.whl (179 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: cchardet
  Building wheel for cchardet (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\cchardet
      copying src\cchardet\version.py -> build\lib.win-amd64-cpython-311\cchardet
      copying src\cchardet\__init__.py -> build\lib.win-amd64-cpython-311\cchardet
      running build_ext
      building 'cchardet._cchardet' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cchardet
  Running setup.py clean for cchardet
Failed to build cchardet
Installing collected packages: cchardet, appdirs, urllib3, tomlkit, pycryptodomex, pycparser, Pillow, pathvalidate, mutagen, multidict, iso8601, idna, frozenlist, crashtest, colorama, charset-normalizer, certifi, attrs, async-timeout, aiofiles, yarl, tqdm, requests, m3u8, click, cleo, cffi, aiosignal, pycares, deezer-py, aiohttp, aiodns, streamrip
  Running setup.py install for cchardet ... error
  error: subprocess-exited-with-error

  × Running setup.py install for cchardet did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running install
      C:\Users\windows7\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\cchardet
      copying src\cchardet\version.py -> build\lib.win-amd64-cpython-311\cchardet
      copying src\cchardet\__init__.py -> build\lib.win-amd64-cpython-311\cchardet
      running build_ext
      building 'cchardet._cchardet' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cchardet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

C:\Users\windows7\Desktop\streamrip-main\New folder>`

**Comment by aniel300** [comment]
will give linux and/or mac os a try next

**Comment by popeye2468** [comment]
you need to install visual tools. then i manually installed cchardet 

have it fully operational on windows 11

**Comment by nwpsys** [comment]
> you need to install visual tools. then i manually installed cchardet
> 
> have it fully operational on windows 11

Thanks. I'll give that a try.

**Comment by aniel300** [comment]
> you need to install visual tools. then i manually installed cchardet
> 
> have it fully operational on windows 11

ok thanks, will give that a try
