### ISSUE TITLE
[Playlist] Would like rip to create actual playlist - ideally in .m3u format

### ISSUE THREAD

**Issue by gahabana** [nathom/streamrip#401]
I prefer to download playlists with actual album and track information (changed in .config file as below) and would like StreamRip to create a playlist of what it had downloaded.
```
[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name.
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = false
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = false
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []
```
... and this is working great. It helps me organize those files into respective artist/album folder as if i have had downloaded entire album rather then just likely one song from it (since it was a part of the playlist).

However, as files are downloaded (with 2 or 3 parallel downloads) not in the order of the playlist - it would be great if streamrip when downloading actual playlist (or maybe anything else if that makes sense) would create playlist file with tracknames of all the songs.
I can take care when reorganizing my library on automatically updating those playlist files to point to correct files but **do not need to re-create playlist file from scratch.**

### Describe the solution you would like.

it would be great if streamrip when downloading actual playlist (or maybe anything else if that makes sense) would create playlist file with tracknames of all the songs.

### Describe alternatives you've considered.

Not aware of alternatives except download playlists with 'wrong' track numbers and album artist names.

**Comment by bohanubis** [comment]
stale bots are stupid man
