### ISSUE TITLE
How this works?

### ISSUE THREAD

**Issue by carrieroent** [nathom/streamrip#402]
How this and others like this works?

Some questions: 
Does this and similar streaming service downloaders use the streaming service's internal APIs? Any service hasn't public APIs for downloading content?

How do you access this API? Do you take the keys from binaries of the official clients?

How do you know how to use these internal APIs? You just guess how it works, reverse engineering it?

How the services cannot prevent this?

Why are these downloaders so often for Deezer and Tidal?

**Comment by nxtmoves** [comment]
Hi @carrieroent, I don't agree on the `enhancement` label.
