### ISSUE TITLE
[FEATURE] --force, --pass

### ISSUE THREAD

**Issue by BitterSweetcandyshop** [nathom/streamrip#405]
### Is the feature request related to a problem. Please describe it.

When downloading an artist on occasion you'll be hit with a track where that specified file path already exists and it completely quits the downloads. This is often because the naming format of just {albumName} without filtering out features causes duplicates since both artists post the EP/Album to their page.

### Describe the solution you would like.

`--pass` where it can continue even after meeting a "already exists, Skipping..."
`--force` where it will overwrite any data.

### Describe alternatives you've considered.

Making my own scripts (tried, lost motive) then submitting a PR

**Comment by parlajatwit** [comment]
you should try making your own scripts again. but i'll take a look at this when i have time, because this is something i want too.

**Comment by Delivator** [comment]
Same problem, any way to fix it?

**Comment by BitterSweetcandyshop** [comment]
No, I ended up giving up again and just moving to orpheus.
