### ISSUE TITLE
[BUG] Scripting with the streamrip library, error -> '400 Client Error: Bad Request for url:' -&- 'Message: 'MD5_ORIGIN''

### ISSUE THREAD

**Issue by QuantumForced** [nathom/streamrip#406]
### Describe the bug

Hello, I copied the code from the wiki page here: https://github.com/nathom/streamrip/wiki/Scripting-with-the-streamrip-library

Changing the client from Deezer to Tidal, I tried to run the script but thus far have only hit the same error, regardless of album url:

`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:`
`https://api.tidalhifi.com/v1/albums/23273346?limit=100`

---

If I try using Deezer instead, here's two examples, I get the following error:

`Unable to stream Mackenzy Mackay - London. Message: 'MD5_ORIGIN'`
&
`Unable to stream BoyWithUke - Out Of Reach. Message: 'MD5_ORIGIN'`

Deezer doesn't error straight away like Tidal, it actually manages to create the album folder and download the cover art, before failing.

---

I should note, the cli version of streamrip works without issue for me with either tidal or deezer, both download .flac smoothly.

Also, no prompts appear asking me to log in to either service when executing either script..

More details below

### Command Used

```bash
tidal_downloader.py:


import streamrip

url = input("Please enter a album url: ")
split_url = url.split("/")
item_type = split_url[-2]  # second to last item

if item_type != "album":
    print("Only album urls are allowed!")
    exit()

album_id = split_url[-1]  # last item

my_deezer_client = streamrip.clients.TidalClient()
my_album = streamrip.media.Album(client=my_deezer_client, id=album_id)
my_album.load_meta()
my_album.download()


-------------------

deezer_downloader.py:


import streamrip  # version 0.7 or greater

url = input("Please enter a deezer album url: ")
split_url = url.split("/")
item_type = split_url[-2]  # second to last item

if item_type != "album":
    print("Only album urls are allowed!")
    exit()

album_id = split_url[-1] # last item

my_deezer_client = streamrip.clients.DeezerClient()
my_album = streamrip.media.Album(client=my_deezer_client, id=album_id)
my_album.load_meta()
my_album.download()
```

### Debug Traceback

```text
tidal_downloader.py:


Please enter a album url: https://listen.tidal.com/album/23273346
Traceback (most recent call last):
  File "C:\Users\ollie\PycharmProjects\REDacted\tidal_downloader.py", line 22, in <module>
    my_album.load_meta()
  File "C:\Users\ollie\PycharmProjects\REDacted\venv\Lib\site-packages\streamrip\media.py", line 1456, in load_meta
    resp = self.client.get(self.id, media_type="album")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollie\PycharmProjects\REDacted\venv\Lib\site-packages\streamrip\clients.py", line 772, in get
    resp = self._api_get(item_id, media_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollie\PycharmProjects\REDacted\venv\Lib\site-packages\streamrip\clients.py", line 1006, in _api_get
    item = self._api_request(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollie\PycharmProjects\REDacted\venv\Lib\site-packages\streamrip\clients.py", line 1047, in _api_request
    r.raise_for_status()
  File "C:\Users\ollie\PycharmProjects\REDacted\venv\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.tidalhifi.com/v1/albums/23273346?limit=100


-------------------

deezer_downloader.py:


Please enter a deezer album url: https://www.deezer.com/en/album/416213967

Downloading London (Album)

Downloading cover art (large)

Unable to stream Mackenzy Mackay - London. Message: 'MD5_ORIGIN'
Traceback (most recent call last):
  File "C:\Users\ollie\PycharmProjects\REDacted\deezer_downloader.py", line 16, in <module>
    my_album.download()
  File "C:\Users\ollie\PycharmProjects\REDacted\venv\Lib\site-packages\streamrip\media.py", line 1205, in download
    raise PartialFailure(failed_downloads)
streamrip.exceptions.PartialFailure
```

### Config File

```toml
I haven't added this as I assume it's not required for the scripting portion of streamrip?
```

### Operating System

Windows

### streamrip version

1.9.7

### Screenshots and recordings

Deezer error in pycharm:
![image](https://user-images.githubusercontent.com/78706210/230727074-24a0c22a-20a8-497f-b5e7-04b7ffa3f29f.png)

Tidal error in pycharm:
![image](https://user-images.githubusercontent.com/78706210/230727144-7c63817d-1f34-4e90-8090-de62fc3ab9a0.png)

### Additional context

I see the template here for bug reporting is for the cli version of streamrip, I have tried my best to fill each section nonetheless - I hope that's ok! This may not even be a bug and perhaps I am doing something wrong - If so, I apologise, any help to get the code working would be super appreciated. I have also added some screenshots. Thank you!

**Comment by QuantumForced** [comment]
**I've made some progress!** I couldn't figure out where to put the login stuff to bypass the credential prompt that's meant to launch, as it didn't show in the wiki entry, but I finally figured it out with both tidal and deezer:

`my_deezer_client = streamrip.clients.TidalClient().login(user_id=user_id, country_code=country_code, access_token=access_token, refresh_token=refresh_token, token_expiry=token_expiry)`
&
`my_deezer_client = streamrip.clients.DeezerClient().login(arl=arl)`

**But I've hit another issue, both tidal and deezer return this same exception:**

`Please enter a album url: https://listen.tidal.com/album/280046343
Logged into Tidal
Traceback (most recent call last):
  File "C:\Users\ollie\PycharmProjects\REDacted\tidal_downloader.py", line 21, in <module>
    my_album.load_meta()
  File "C:\Users\ollie\PycharmProjects\REDacted\venv\Lib\site-packages\streamrip\media.py", line 1456, in load_meta
    resp = self.client.get(self.id, media_type="album")
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'`

Any idea?

**Comment by nathom** [comment]
You are assigning the result of the `login` call to `my_deezer_client`, not the client object itself. Try this:

```python
client = streamrip.clients.TidalClient()
client.login(...)
# download items
```

**Comment by QuantumForced** [comment]
> You are assigning the result of the `login` call to `my_deezer_client`, not the client object itself. Try this:
> 
> ```python
> client = streamrip.clients.TidalClient()
> client.login(...)
> # download items
> ```

That fixed it!! I can't thank you enough

While I have you, if you don't mind me asking: how would I go about setting the following options:

- Metadata tags to exclude
- Artwork size, dimension
- Download quality (integer)

They are very easy to set in the config file for streamrip cli downloading, but I'm not sure how they are set via streamrip scripting.

Thanks again for your time and assistance

**Comment by dracarys69** [comment]
how did you manage to fix the deezer issue @QuantumForced
