### ISSUE TITLE
[FEATURE] Deezer - Multiple artists

### ISSUE THREAD

**Issue by Sbf93** [nathom/streamrip#418]
### Is the feature request related to a problem. Please describe it.

When I rip an album from Deezer, all Songs always have only one artist tagged.
When a song is created by more than one artist, everyone after the first one is completely ignored.

### Describe the solution you would like.

I would like to have a few options in the config file to get all artists.

Option 1:
All artists are tagged in the artist-field, seperated by a custom string.
Examples:
Artist 1; Artist 2; Artist 3
Artist 1 / Artist 2 / Artist 3

Option 2:
All artist after the first one are added to the title like this:
Songtitle (feat. Artist 2, Artist 3)

Option 3:
(This one is not relevant for me, but I guess, it could be useful for other users.)
Create a seperate artist tag for every artist.

### Describe alternatives you've considered.

After downloading an album, I use third party tools (Mp3tag, TagScanner) to manually correct the tags or overwrite all tags with a third party source (MusicBrainz, Discogs).

**Comment by AKL55** [comment]
Would be nice to have.
i'm manually tagging the artists currently.

**Comment by arli2001** [comment]
You can use the fork on my profile meanwhile, it's not very clean but it works

**Comment by AKL55** [comment]
> You can use the fork on my profile meanwhile, it's not very clean but it works

Thanks, tested and worked well.

**Comment by Sbf93** [comment]
> You can use the fork on my profile meanwhile, it's not very clean but it works

Thank you very much!

**Comment by sureshfizzy** [comment]
@arli2001 rip url https://www.qobuz.com/us-en/album/rumours-fleetwood-mac/0603497941032
Updating config file to new version. Some settings may be lost.

  NonExistentKey

  'Key "email" does not exist.'

  at .local/lib/python3.10/site-packages/tomlkit/container.py:553 in __getitem__
      549│             key = Key(key)
      550│
      551│         idx = self._map.get(key, None)
      552│         if idx is None:
    → 553│             raise NonExistentKey(key)
      554│
      555│         if isinstance(idx, tuple):
      556│             # The item we are getting is an out of order table
      557│             # so we need a proxy to retrieve the proper objects
i get this error any idea ?

**Comment by arli2001** [comment]
I will try and update my fork soon, since the code has been refactored

**Comment by arli2001** [comment]
@sureshfizzy the fork is now up to date, it was even easier with the refactoring :) I'll open a pull request by the way
