### ISSUE TITLE
[BUG] Deezloader download fails with message about migrating to some loader app

### ISSUE THREAD

**Issue by aaronliu0130** [nathom/streamrip#431]
### Describe the bug

Downloads from Deezer fail with "It's been a long time - We have shut down our backend. We are sorry. Please migrate to the loader app (loaderapp.info) for a better experience." for every song.

### Command Used

```bash
rip url https://www.deezer.com/en/track/13111714
```

### Debug Traceback

<details>
<summary>rip url https://www.deezer.com/en/track/13111714 -vvv</summary>
<pre>
Falling back to Deezloader (unstable). If you have a subscription, run rip config --deezer to log in.
Downloading Rick Astley - Never Gonna Give You Up

Cover |███████████████████████████████████████████████████████████████████████████████████████| 00:00 left at 96.5MB/s
Unable to stream Rick Astley - Never Gonna Give You Up. Message: It's been a long time - We have shut down our backend. We are sorry. Please migrate to the loader app (loaderapp.info) for a better experience.
PS C:\Users\aaron\Music\dan> rip url https://www.deezer.com/en/track/13111714 -vvv
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Parsed urls: [('deezer', 'track', '13111714')]
DEBUG:streamrip:Searching for {'id': '13111714'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
Falling back to Deezloader (unstable). If you have a subscription, run rip config --deezer to log in.
DEBUG:streamrip:{'id': '13111714'}
DEBUG:streamrip:{'downloads': {'folder': 'C:\\Users\\aaron\\StreamripDownloads', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3}}, 'qobuz': {'quality': 3, 'download_booklets': True, 'email': '', 'password': '', 'app_id': '', 'secrets': []}, 'tidal': {'quality': 3, 'download_videos': True, 'user_id': '', 'country_code': '', 'access_token': '', 'refresh_token': '', 'token_expiry': ''}, 'deezer': {'quality': 2, 'arl': '', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': '', 'app_version': ''}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': 'C:\\Users\\aaron\\AppData\\Local\\streamrip\\streamrip\\downloads.db'}, 'failed_downloads': {'enabled': True, 'path': 'C:\\Users\\aaron\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'large', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': []}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'restrict_characters': False, 'truncate': True}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.9.6'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'truncate_filenames': True, 'parent_folder': 'C:\\Users\\aaron\\StreamripDownloads', 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'embed_cover': True, 'embed_cover_size': 'large', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'concurrent_downloads': True, 'max_connections': 3, 'new_tracknumbers': True, 'download_videos': True, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': []}
DEBUG:streamrip:Loading metadata
DEBUG:streamrip:{'id': 13111714, 'readable': False, 'title': 'Never Gonna Give You Up', 'title_short': 'Never Gonna Give You Up', 'title_version': '', 'isrc': 'GBARL9300135', 'link': 'https://www.deezer.com/track/13111714', 'share': 'https://www.deezer.com/track/13111714?utm_source=deezer&utm_content=track-13111714&utm_term=0_1688526264&utm_medium=web', 'duration': 211, 'track_position': 2, 'disk_number': 1, 'rank': 21131, 'release_date': '2011-09-09', 'explicit_lyrics': False, 'explicit_content_lyrics': 0, 'explicit_content_cover': 2, 'preview': 'https://cdns-preview-2.dzcdn.net/stream/c-2279f049ff1aa1b156e2a974da4a2b5d-3.mp3', 'bpm': 113.3, 'gain': -10.7, 'available_countries': [], 'contributors': [{'id': 6160, 'name': 'Rick Astley', 'link': 'https://www.deezer.com/artist/6160', 'share': 'https://www.deezer.com/artist/6160?utm_source=deezer&utm_content=artist-6160&utm_term=0_1688526264&utm_medium=web', 'picture': 'https://api.deezer.com/artist/6160/image', 'picture_small': 'https://e-cdns-images.dzcdn.net/images/artist/572ff4d8a877291e3abfb4c17f570233/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://e-cdns-images.dzcdn.net/images/artist/572ff4d8a877291e3abfb4c17f570233/250x250-000000-80-0-0.jpg', 'picture_big': 'https://e-cdns-images.dzcdn.net/images/artist/572ff4d8a877291e3abfb4c17f570233/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://e-cdns-images.dzcdn.net/images/artist/572ff4d8a877291e3abfb4c17f570233/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/6160/top?limit=50', 'type': 'artist', 'role': 'Main'}], 'md5_image': '5e52cfce539d663bd2d5023f25c80916', 'artist': {'id': 6160, 'name': 'Rick Astley', 'link': 'https://www.deezer.com/artist/6160', 'share': 'https://www.deezer.com/artist/6160?utm_source=deezer&utm_content=artist-6160&utm_term=0_1688526264&utm_medium=web', 'picture': 'https://api.deezer.com/artist/6160/image', 'picture_small': 'https://e-cdns-images.dzcdn.net/images/artist/572ff4d8a877291e3abfb4c17f570233/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://e-cdns-images.dzcdn.net/images/artist/572ff4d8a877291e3abfb4c17f570233/250x250-000000-80-0-0.jpg', 'picture_big': 'https://e-cdns-images.dzcdn.net/images/artist/572ff4d8a877291e3abfb4c17f570233/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://e-cdns-images.dzcdn.net/images/artist/572ff4d8a877291e3abfb4c17f570233/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/6160/top?limit=50', 'type': 'artist'}, 'album': {'id': 1203570, 'title': 'The Best Year Of My Life: 1987', 'link': 'https://www.deezer.com/album/1203570', 'cover': 'https://api.deezer.com/album/1203570/image', 'cover_small': 'https://e-cdns-images.dzcdn.net/images/cover/5e52cfce539d663bd2d5023f25c80916/56x56-000000-80-0-0.jpg', 'cover_medium': 'https://e-cdns-images.dzcdn.net/images/cover/5e52cfce539d663bd2d5023f25c80916/250x250-000000-80-0-0.jpg', 'cover_big': 'https://e-cdns-images.dzcdn.net/images/cover/5e52cfce539d663bd2d5023f25c80916/500x500-000000-80-0-0.jpg', 'cover_xl': 'https://e-cdns-images.dzcdn.net/images/cover/5e52cfce539d663bd2d5023f25c80916/1000x1000-000000-80-0-0.jpg', 'md5_image': '5e52cfce539d663bd2d5023f25c80916', 'release_date': '2011-09-09', 'tracklist': 'https://api.deezer.com/album/1203570/tracks', 'type': 'album'}, 'type': 'track'}
Downloading Rick Astley - Never Gonna Give You Up

DEBUG:streamrip:Track meta formatter {'tracknumber': 2, 'artist': 'Rick Astley', 'albumartist': None, 'composer': None, 'title': 'Never Gonna Give You Up', 'albumcomposer': None, 'explicit': False}
DEBUG:streamrip:Formatter keys: {tracknumber}. {artist} - {title}{explicit}
DEBUG:streamrip:'tracknumber'
DEBUG:streamrip:2
DEBUG:streamrip:2
DEBUG:streamrip:'artist'
DEBUG:streamrip:Rick Astley
DEBUG:streamrip:1
DEBUG:streamrip:'title'
DEBUG:streamrip:Never Gonna Give You Up
DEBUG:streamrip:1
DEBUG:streamrip:'explicit'
DEBUG:streamrip:False
DEBUG:streamrip:3
DEBUG:streamrip:Formatted path: C:\Users\aaron\StreamripDownloads\02. Rick Astley - Never Gonna Give You Up.flac
DEBUG:streamrip:Downloading cover from https://e-cdns-images.dzcdn.net/images/cover/5e52cfce539d663bd2d5023f25c80916/500x500-000000-80-0-0.jpg
Cover |███████████████████████████████████████████████████████████████████████████████████████| 00:00 left at 20.0MB/s
DEBUG:streamrip:Download url http://dz.loaderapp.info/deezer/1411/https://api.deezer.com/track/13111714
Unable to stream Rick Astley - Never Gonna Give You Up. Message: It's been a long time - We have shut down our backend. We are sorry. Please migrate to the loader app (loaderapp.info) for a better experience.
DEBUG:streamrip:Executing INSERT INTO failed_downloads (source, media_type, id) VALUES (?, ?, ?)
DEBUG:streamrip:Items to add: ('deezer', 'track', '13111714')
DEBUG:streamrip:UNIQUE constraint failed: failed_downloads.id
</pre></details>

### Config File

<details>
<summary>It's the default</summary>
<pre>
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\wowsupersecretcredentials\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = "C:\\Users\\aaron\\AppData\\Local\\streamrip\\streamrip\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

[database.failed_downloads]
enabled = true
path = "C:\\Users\\aaron\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.

[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.

[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true

# Last.fm playlists are downloaded by searching for the titles of the tracks

[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"

[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.6"
</pre></details>

### Operating System

Windows

### streamrip version

1.9.7

### Screenshots and recordings

Huh, for Windows you can use PowerSession-rs. I believe the above are enough though.

**Comment by arli2001** [comment]
Have you run `rip config --deezer` as suggested?

**Comment by aaronliu0130** [comment]
I don't have a subscription.

**Comment by aaronliu0130** [comment]
I don’t have a subscription.

**Comment by aaronliu0130** [comment]
I don’t have a subscription.

**Comment by aaronliu0130** [comment]
Excuse me‽ I said stuff! 

Could someone from this repository replace the probot with actions/stale?

**Comment by nathom** [comment]
Deezloader shut down, so free deezer downloads no longer work unfortunately. You need an account.

**Comment by aaronliu0130** [comment]
Ah.
