### ISSUE TITLE
Download path in Termux-Mobile

### ISSUE THREAD

**Issue by badboy-14** [nathom/streamrip#44]
Hey,
Thanks for the work. I am using Termux in mobile, I have downloaded few tracks but I am not able to identify the downloaded path in mobile phone. Could you please guide me how to set download path in Termux-Mobile. Thanks!

**Comment by nathom** [comment]
I'm not familiar with that app, but you can get the file path of the config file using `rip config --open`, which will contain the downloads path.

**Comment by badboy-14** [comment]
Yes, the file will open but when I get into the path I do not have folder named with Steamrip download. After editing the file I can't able to save from termux

**Comment by badboy-14** [comment]
Thanks for your time

**Comment by nathom** [comment]
Then it must be an issue with the app, not streamrip. Unfortunately I cannot help you with that. Maybe you can ask for help on a forum.

**Comment by AminurAlam** [comment]
@nathom the directory where the config file is present cannot be accessed unless your device is rooted which makes it impossible for me to change anything in it

`/data/data/com.termux/files/home/.config/streamrip/config.toml`

is there still any way to edit the file?
