### ISSUE TITLE
[BUG] Not actually a bug, just struggling with installing streamrip.

### ISSUE THREAD

**Issue by GZ2E01** [nathom/streamrip#440]
### Describe the bug

Hi, I'm rather new to Python and tried installing streamrip today, with no success. I have pip and the commands worked but
`'rip' is not recognized as an internal or external command, operable program or batch file.` I've heard that this issue should be fixed with adding something to Path but i have no clue how all that works. If anyone could help me out with this it would be greatly appreciated. Thank you

![image](https://github.com/nathom/streamrip/assets/106167103/e5747689-053d-4942-b5b4-7a16571f95ad)

### Command Used

```bash
rip
```

### Debug Traceback

```text
Can't access it
```

### Config File

```toml
Can't access it.
```

### Operating System

Windows

### streamrip version

Newest I think, I have no way of checking

### Screenshots and recordings

![image](https://github.com/nathom/streamrip/assets/106167103/d5c6db06-bfb0-4258-9351-4a9425523e32)

### Additional context

I am not good at Python

**Comment by reaitten** [comment]
Please try running the command `python3 -m rip`, `python -m rip` or `py -m rip` and see which ones work for you. You can also follow what [Call190Now](https://github.com/Call190Now) has suggested.

**Comment by GZ2E01** [comment]
Hi, sorry for not responding to both of the suggestions. I am currently away from my PC and will be trying these when I go back to my hometown in a couple days, the PATH one should almost definitely work
