### ISSUE TITLE
[FEATURE] Longer Folder Titles

### ISSUE THREAD

**Issue by animelol123** [nathom/streamrip#445]
### Is the feature request related to a problem. Please describe it.

When using streamrip it would cut off the last part of the folder name on longer album names with the streamrip naming scheme. An example of this would be the following:

Folder name cuting off would have the finished album in a folder called 
`Gareth Coker, League of Legends, Riot Forge - The Mageseeker A League of Legends Story ((Official Soundtrack)) (2023) [F`
instead of 
`Gareth Coker, League of Legends, Riot Forge - The Mageseeker A League of Legends Story ((Official Soundtrack)) (2023) [FLAC] [24B-48kHz]`

Cause of this I need to add the rest by hand. Is it possible to fix this?

### Describe the solution you would like.

Fix for longer folder titles

**Comment by Batmanx86** [comment]
try setting `truncate = false` in config.toml
