### ISSUE TITLE
[FEATURE] Move the Streamrip install in a different location

### ISSUE THREAD

**Issue by Piggoz** [nathom/streamrip#455]
### Is the feature request related to a problem. Please describe it.

Can we `move` the Strearip install in a different location or simply istall it in the location we do prefer?

I try to simply move the folder to my desired location after install and basically the program works, then I'm unable to configure anything. It complain it can't find the config.toml file and even if I create it in the location it ask me to create it, the file is not read.

I also have this problem when I try to add my legit Deezer ARL to my Streamrip config file and I don't know if it is becouse I moved the program or becouse it is a bug:

`E:\streamrip>rip config --deezer <my arl>

  RuntimeException

  No arguments expected for "config" command, got "<my arl>"

  at ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cleo\io\inputs\argv_input.py:258 in _parse_argument
      254│                 )
      255│             else:
      256│                 message = 'No arguments expected, got "{}"'.format(token)
      257│
    → 258│             raise RuntimeException(message)
      259│
      260│     def _add_short_option(self, shortcut: str, value: Any) -> None:
      261│         if not self._definition.has_shortcut(shortcut):
      262│             raise NoSuchOptionException(f'The option "-{shortcut}" does not exist')

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose`

My version of python is:

`E:\streamrip>python --version
Python 3.10.11`

Streamrip version:

`E:\streamrip>rip --version
Rip (version 1.9.7)`

Last but not least: how to uninstall the program and all it's related file if I need it or if I just want to move it in a different location or reset it?

Thankx in advance

### Describe the solution you would like.

I would like to be able to install streamrip on a specific location I do choose.

**Comment by nathom** [comment]
You need to create a symlink for this behavior.

**Comment by Piggoz** [comment]
Hi Nathan and thank you very much for your promot reply. Considering i’m on Windows I should create Junction, then based on the code I poated above I kindly ask for your help.

I juat moved the folder from my Appdata folder to the e:\ drive and as I said I can rum the program then I can’t uodate configuration.

i also tryed to remove streamrip completely the I failed with it. And running the —upgrade switxh didn’t help.

Thankx again if you can help me with some usefull command to fix the situation.

thankx in advance.

**Comment by nathom** [comment]
Try this:

https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

Make sure to try with soft and hard links.
