### ISSUE TITLE
[LOGO] <suggestion>

### ISSUE THREAD

**Issue by bascurtiz** [nathom/streamrip#458]
### Is the feature request related to a problem. Please describe it.

streamrip currently is missing a logo.

### Describe the solution you would like.

a solution could be using the logo i created.

### Describe alternatives you've considered.

![streamrip-logo-bas-curtiz](https://github.com/nathom/streamrip/assets/34075088/c1154e49-673b-4ec9-a791-57f42a437df9)

**Comment by nathom** [comment]
Ooh, this is cool. Open a PR adding the SVGs in a folder.

**Comment by bascurtiz** [comment]
Meh, too much hassle :)
I suggest right-click the svg, save it, and add it to your readme?
