### ISSUE TITLE
[FEATURE] Allow to limit max resolution of saved covers

### ISSUE THREAD

**Issue by entrider** [nathom/streamrip#469]
### Is the feature request related to a problem. Please describe it.

It's not possible to limit the size of saved covers (like it can be done for embedded ones) and for qobuz, for example, the "original" quality is huge (6000x6000px).

### Describe the solution you would like.

It'd be nice to have a possibility to specify maximum allowed resolution for saved covers. For me personally even 1280x1280px (Tidal) and 1400x1400 (Deezer) is too much, and I'd like to be able to set the max resolution to say 640x640px in order to get this (or lower) resolution from all services. It can be accomplished by adding new options like `max_hires_width` and `max_hires_height` or just `hires_size` (thumbnail, small, large, original), for example.

**Comment by nathom** [comment]
This is already possible in the artwork section of the config file.

**Comment by entrider** [comment]
bump

**Comment by nathom** [comment]
Implemented in v2. Should be merged I to dev within the next few weeks.
