### ISSUE TITLE
[FEATURE] StreamRip Windows Version

### ISSUE THREAD

**Issue by Mojas84** [nathom/streamrip#474]
### Is the feature request related to a problem. Please describe it.

Hi. Please create windows version for this awesome app on download Deezer Hifi files......

### Describe the solution you would like.

StreamRip Windows Version

**Comment by nathom** [comment]
It works on windows. Just follow the installation instructions in the wiki :)

**Comment by Mojas84** [comment]
Hi sorry not me work i have python 3.12. I Reinstaled on 3.8 StreamRip Work Super Application. Very MUch thanks
