### ISSUE TITLE
[FEATURE] Search for a singular track

### ISSUE THREAD

**Issue by oopsitsdeleted** [nathom/streamrip#479]
### Is the feature request related to a problem. Please describe it.

I want it to be possible to search for singular tracks when using rip search instead of searching for albums only.

### Describe the solution you would like.

maybe have a flag that enables someone to search for individual tracks instead of whole albums

### Describe alternatives you've considered.

I currently share the link to the individual song I want then replace 'open' in open.qobuz.com to 'play'. this is really inconvenient

**Comment by nathom** [comment]
Implemented in v2
