### ISSUE TITLE
Possible syntax error?

### ISSUE THREAD

**Issue by co1ncidence** [nathom/streamrip#49]
Upon usage of any `rip` command I get the following error from python:

![image](https://user-images.githubusercontent.com/62483590/114479440-2a461d00-9bc6-11eb-8e11-3711690129b2.png)

I've looked at the source file (line 110) and this is what my linter (flake8) says:

![image](https://user-images.githubusercontent.com/62483590/114479607-798c4d80-9bc6-11eb-87b9-14a95f6b9702.png)

I'm not familiar with python syntax and trying to look up how if statements work in it only led me to be more confused.

Oh, and removing the "whitespace before :" just leads to an E999 (for the flake8 python checker), which is just a rabbit hole if you try googling it.

If you need any more information, let me know.

**Comment by co1ncidence** [comment]
UPDATE:

![image](https://user-images.githubusercontent.com/62483590/114479979-37174080-9bc7-11eb-9d64-c2ed342b86f0.png)

The error seems to happen in a couple other places as well (line 1357 in `downloader.py`, for example, and I believe this is a cross-file problem, as trying to fix it in `downloader.py` leads to the same response in *other* files.

**Comment by nathom** [comment]
You need to update your version of Python, which does not support the `:=` operator.

**Comment by co1ncidence** [comment]
lmfao
