### ISSUE TITLE
[BUG] Attempting to rip a deezer artist multiple times when a new release comes out does not rip new album

### ISSUE THREAD

**Issue by mon5termatt** [nathom/streamrip#493]
### Describe the bug

Attempting to rip a deezer artist multiple times when a new release comes out does not rip new album, instead errors out saying old albums exist already.

### Command Used

```bash
rip url https://www.deezer.com/us/artist/$1 --config=/plex/streamrip/configs/artist.toml $2


(rip url https://www.deezer.com/us/artist/1353172 --config=/plex/streamrip/configs/artist.toml)
```

### Debug Traceback

```text
https://bin.meme.beer/?c25b2fcd772e108d#8EdCotmjoxsfNHKL1G8h7DuQaseCb5x5SBUR9Uuw3Wwh
```

### Config File

```toml
https://bin.meme.beer/?b3f4f4f54645cbec#FuiZMoHCHXsbQNYtdJhXmNkvzsRgkK5k66FNg5hAaT8U
```

### Operating System

Debian 12

### streamrip version

1.9.7

**Comment by mon5termatt** [comment]
It would be nice if instead of error out after finding the existing album it would just skip THAT album and continue down the list.

you can use -i to fix this issue.

**Comment by nathom** [comment]
This is because the artist ID is logged in the DB as downloaded. This behavior has been changed in v2 so that only track IDs are logged. The artists you previously downloaded will, however, continue to be skipped (unless you reset the database or use `-i`).

**Comment by mon5termatt** [comment]
V2 sounds like it's going to be awesome. Let me know when it's planned and I can test anything if you need. I'm running this as a dedicated VM.

**Comment by nathom** [comment]
@mon5termatt Please do test it. It's live on the dev branch! 95% of the features should be implemente and most of the bugs are fixed.
