### ISSUE TITLE
[FEATURE] Use actions/stale instead of Probot

### ISSUE THREAD

**Issue by aaronliu0130** [nathom/streamrip#494]
### Is the feature request related to a problem. Please describe it.

I responded to the stalebot a couple days ago AND IT STILL CLOSED MY ISSUE

Plus stalebot is deprecated already, check their repository

### Describe the solution you would like.

Use https://github.com/actions/stale

### Describe alternatives you've considered.

i said just nuke the bot

**Comment by nathom** [comment]
Fixed

**Comment by aaronliu0130** [comment]
Thanks! Could someone reopen the mistankenly staled #431 ?
