### ISSUE TITLE
[FEATURE] - Download additional settings 

### ISSUE THREAD

**Issue by frank01wong** [nathom/streamrip#496]
### Is the feature request related to a problem. Please describe it.

Some of the playlist i aim to acquire are very large (1k-2k+ tracks). Would like the ability to limit the download quantify per hour or per batch...

### Describe the solution you would like.

Parameter for number of concurrent download (currently up to 3) to also feature
limitation per URL per unit of time (minute, hour, days).

**Comment by nathom** [comment]
Specifying max concurrent downloads and a rate limit are available in v2 on the dev branch.
