### ISSUE TITLE
[FEATURE] Easier Bulk Downloading

### ISSUE THREAD

**Issue by TheGMan1776** [nathom/streamrip#498]
### Is the feature request related to a problem. Please describe it.

No

### Describe the solution you would like.

(All in relation to Tidal fyi)

-Right now I'm trying to save Frank Sinatra but he has A LOT of albums for me to go through and make sure I only get the ones I want because I'm not too worried about live version and all this other stuff I just want the highest quality lossless studio releases. But I think it would be nice if I could instead of putting all the albums links just put in an artist link and have it download everything from that artist and then I can just easily delete what I don't want. 

-Also clarification on what "rip repair" does because I always use the "rip url --file urls.txt --max-quality 3" command and I know the quality is set to lossless and the "rip repair" command seems to always get the same lossless files but I couldn't find anywhere where it said for sure or not if "rip repair" remembered the set quality.

-Another nice feature would be proxy support so that we could have a text file called "proxies" and streamrip would run through the proxies and automatically switch proxies after whatever set number or songs or after it detects songs failing to download. Because if I try to download too many songs Tidal starts giving errors saying too many requests because they're all coming from my 1 IP.

Those are somethings I would LOVE to see but great work StreamRip as is, its already really good.

### Describe alternatives you've considered.

Manually adding each album link I want, running "rip repair" and manually checking the files to make sure they are lossless, and just waiting for my IP to cool down so I can download more songs.

**Comment by nathom** [comment]
Does downloading the artist link work?

**Comment by TheGMan1776** [comment]
> Does downloading the artist link work?

I have 2 installs of StreamRip on 2 different PCs and for some reason they seem to be acting a little different when I use the same commands, signed into the same Tidal account, with the StreamRip config configured the same way. 
I mentioned part of it here (https://github.com/nathom/streamrip/issues/475#issuecomment-1857204171)
But in relation to using the artist link. On PC 1 (Which is the PC I said gave the message of the file already existing in my other comment) I try to use the artist link and then it downloads 1 random album from the artist and gives the message saying the file already exist and doesn't download (or redownload) anything else. (Which as mentioned in my other comment might be because its trying to redownload the same thing but finding the file and saying it already exists PC 1 is at least) On PC 2 if I use the artist link it appears to go through and start downloading more then 1 album BUT it has the problem me and "CHJ85" were talking about here "https://github.com/nathom/streamrip/issues/475#issuecomment-1857204171" where it's downloading multiple versions of the same songs. Sorry if this is confusing to read and for all the back and forth but as typing this it dawned on me that that is probably why just using the artist link doesn't work or has issues

**Comment by TheGMan1776** [comment]
[PC 1 config.txt](https://github.com/nathom/streamrip/files/13680619/PC.1.config.txt)
[PC 2 config.txt](https://github.com/nathom/streamrip/files/13680620/PC.2.config.txt)

Those are the 2 config files from each PC (Changed to .txt files so I could upload them to GitHub)

**Comment by nathom** [comment]
Try using v2 on the `dev` branch. It ignores existing files.

**Comment by Carter0108** [comment]
Another idea for bulk downloading: would it be possible to use the search function to simply write the URL to a file so you could gather a load of artists together and then download all at once? It would be less tedious than gathering the URLs manually.

**Comment by nathom** [comment]
@Carter0108  Yes I could do that. Can you make a separate enhancement issue for it?

**Comment by nathom** [comment]
Creating new issue for proxy support. Remaining issues raised seem to be resolved in v2.
