### ISSUE TITLE
No tracks available for download on Deezer. 

### ISSUE THREAD

**Issue by gjgjDMC** [nathom/streamrip#50]
All music on Deezer is not downloadable. The album art gets downloaded perfectly fine, but no matter what song or album I choose, it would download the album art and all tracks will be "not available for download". 
Not really too experienced with computer stuff but I can give you more information if you can tell me how to obtain them. 
![streamrip issue 1](https://user-images.githubusercontent.com/24213871/114487070-f0ccdc00-9bdc-11eb-9c5b-88e3a0ae105f.PNG)

**Comment by nathom** [comment]
Seems like the Deezloader server is down. I'm going to wait it out for a week or so, to see if it comes back up. If not, I might have to remove the free downloads.

**Comment by javierlopezdeancos** [comment]
ouch!!!, seems like follow not available

**Comment by Gamer4Life2020** [comment]
I never had any luck with Deezer, but I do know you have to be logged-in Deezer changed that awhile back. Most use the ARL to do so. I never got any prompt to log-in or add ARL. I know Freezer/Deemix use ARL.

**Comment by nathom** [comment]
Deezer is back up 🥳
