### ISSUE TITLE
[FEATURE] Add URL metadata like youtube-dl

### ISSUE THREAD

**Issue by AttractLight** [nathom/streamrip#515]
### Is the feature request related to a problem. Please describe it.

I have an issue when I want to know where a file was downloaded from.

### Describe the solution you would like.

I would like streamrip to add URL metadata. youtube-dl (or maybe yt-dlp?) adds URL to the `comment` metadata when `--add-metadata` is specified. The `WWW` metadata would also be nice for such a URL.

### Describe alternatives you've considered.

Currently streamrip supports `{id}` in `folder_format`. However, some of them seem to be internal identifiers. I don't even know if I can download with these ids on streamrip.

**Comment by nathom** [comment]
Try `rip id` on v2.

**Comment by AttractLight** [comment]
Qobuz seems working only for tracks? I tried to download an album with a numeric ID but I got "No result matching given argument". Somehow I could download a track with another numeric ID.
