### ISSUE TITLE
[BUG] I am unable to rip discographys from qobuz

### ISSUE THREAD

**Issue by sarge1996** [nathom/streamrip#516]
### Describe the bug

Cannot get interpreter urls to find artist id. I have tried and failed on the release version and now the dev version. not sure if I am just doing something wrong as it works on tidal, and individual albums work for qobuz, just take time

### Command Used

```bash
rip url https://www.qobuz.com/ca-en/interpreter/busta-rhymes/62425
```

### Debug Traceback

```text
get a no such option error when trying
```

### Config File

```toml
config file is brand new and unchanged
```

### Operating System

windows 10

### streamrip version

v 2.0

### Additional context

Hope I make sense, I am incredibly new to the command line, this is the only program I have been able to get working at all

**Comment by nathom** [comment]
Fixed in v2
