### ISSUE TITLE
Can't download TIDAL video.

### ISSUE THREAD

**Issue by CyberLykan** [nathom/streamrip#52]
Link: https://tidal.com/browse/video/172107685

> Traceback (most recent call last):
>   File "d:\programdata\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "d:\programdata\miniconda3\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "D:\ProgramData\Miniconda3\Scripts\rip.exe\__main__.py", line 7, in <module>
>   File "d:\programdata\miniconda3\lib\site-packages\streamrip\cli.py", line 288, in main
>     cli(obj={})
>   File "d:\programdata\miniconda3\lib\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "d:\programdata\miniconda3\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "d:\programdata\miniconda3\lib\site-packages\click\core.py", line 1236, in invoke
>     return Command.invoke(self, ctx)
>   File "d:\programdata\miniconda3\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "d:\programdata\miniconda3\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "d:\programdata\miniconda3\lib\site-packages\click\decorators.py", line 21, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "d:\programdata\miniconda3\lib\site-packages\streamrip\cli.py", line 96, in cli
>     core.handle_urls(kwargs["urls"])
>   File "d:\programdata\miniconda3\lib\site-packages\streamrip\core.py", line 141, in handle_urls
>     self.handle_item(source, url_type, item_id)
>   File "d:\programdata\miniconda3\lib\site-packages\streamrip\core.py", line 152, in handle_item
>     assert media_type in MEDIA_TYPES, media_type
> AssertionError

**Comment by CyberLykan** [comment]
Also breaks if the tool encounters a video in a deluxe video album.

**Comment by nathom** [comment]
`streamrip` doesn't support TIDAL videos currently. If you would like to see that as a feature, open a "Feature Request" Issue. Thanks.
