### ISSUE TITLE
Open Config File

### ISSUE THREAD

**Issue by G5dwe1** [nathom/streamrip#522]
### Describe the bug

I see that in every bug report there is a config file. I want to ask how to open it. Sorry for this stupid question

### Command Used

```bash
Rip config
```

### Debug Traceback

```text
N
```

### Config File

```toml
N
```

### Operating System

Android

### streamrip version

1.9.7

**Comment by mon5termatt** [comment]
this isnt a bug and you should be able to work with config files in a text editor.

**Comment by nathom** [comment]
`rip config --help`
