### ISSUE TITLE
Streamrip Python 3.8.8 failed install new version

### ISSUE THREAD

**Issue by Mojas84** [nathom/streamrip#565]
### Describe the bug

Hi how version python have installed newer version. Me work on python 3.8.8 onnly 1.9.7 with pip3 install git+https://github.com/nathom/streamrip.git@dev not work latest version. Write = ERROR: Package 'streamrip' requires a different Python: 3.8.8 not in '>=3.10,<4.0'

### Command Used

```bash
pip3 install git+https://github.com/nathom/streamrip.git@dev
```

### Debug Traceback

```text
....
```

### Config File

```toml
.....
```

### Operating System

Windows

### streamrip version

2.0.3

**Comment by nathom** [comment]
Not a bug. V2 requires python 3.10

**Comment by Mojas84** [comment]
Ok sorry.
