### ISSUE TITLE
[FEATURE] tracks number

### ISSUE THREAD

**Issue by thedaa** [nathom/streamrip#572]
### Is the feature request related to a problem. Please describe it.

Hello, in the previous version i used 1. something the 9 first tracks were starting with a 0, which i think is way better for files management. Is there a reason you changed this ? 

### Describe the solution you would like.

I'd like it to be like before if the change was not intended.

**Comment by naiches** [comment]
Same issue here, this seems to be a bug. I use MP3Tag to fix this manually for now `$num(%track%,2)`.

**Comment by celly69** [comment]
latest version disappoint me because of this, i end up with downgrade streamrip version

**Comment by nathom** [comment]
You can do this by using padding specifiers in the format string:

```toml
[filepaths]
# ...
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
```

I can make this a default in the next version.

**Comment by jieweix** [comment]
> I can make this a default in the next version.

Please do!
