### ISSUE TITLE
[FEATURE] Additional documentation on adding Rip to PATH 

### ISSUE THREAD

**Issue by tannerbaum** [nathom/streamrip#578]
### Is the feature request related to a problem. Please describe it.

I have been unable to execute streamrip after installing on MacOS (M1). I have been trying to read the troubleshooting guide, and am struggling with this step:

> This should output something like Rip (version 1.2). If you get a command not found message, you need to add the rip program to your PATH (Path for Windows).

It is most likely some combination of lack of Python or PATH knowledge that is setting me back here. 

### Describe the solution you would like.

An additional sentence or two at this location in the docs on what to add to our PATH specifically. 

### Describe alternatives you've considered.

I tried running `pip3 show streamrip` and was told that the package is located in `/Users/foo/Library/Python/3.9/lib/python/site-packages`. I use zsh so I have tried appending variations of `export PATH="/Users/foo/Library/Python/3.9/lib/python/site-packages/rip/__main__.py:$PATH"` to my .zshrc but no luck. 

Thanks! Looking forward to trying out the package.

**Comment by tannerbaum** [comment]
I believe the magic line for me ended up being: 

`export PATH="/Users/foo/Library/Python/3.9/bin:$PATH"`

I had missed that there was a bin folder there too, which makes more sense in hindsight.

**Comment by nathom** [comment]
Are these instructions better?

https://github.com/nathom/streamrip/wiki

Feel free to modify the Wiki if theres other info you think would be helpful.

**Comment by tannerbaum** [comment]
@nathom Since I had to install on a new machine and ran into this again, I attempted to add to the wiki a couple of notes. Thanks!
