### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by utubeonly007** [nathom/streamrip#61]
I am new to GitHub, command line and Python, so I don't know very well how these things work. Maybe the documentation could be made more beginner friendly.

For installing streamrip, I first installed Python, because if you click on the link to install pip, they say it comes installed with Python. So I installed the latest version of Python, v3.9.4. So maybe that's something you could simplify in the documentation.

Next, I verified pip was installed using
`py -m pip --version`
It showed the version and path of pip (in site-packages)

To install streamrip, I opened Windows Terminal (tried with CMD prompt too), followed the instructions and typed in:
`pip3 install streamrip windows-curses --upgrade`
I get the error:
The term 'pip3' is not recognized as the name of a cmdlet, function, script file, or operable program.
I also tried with 'pip' instead of 'pip3', but still got the same error.

Looked a little bit more on the pip install page, saw that the following could work:
`py -m pip install streamrip windows-curses --upgrade`
And that worked.

I don't want to use conversion, so I skipped ffmpeg.
I want to download only from Qobuz, so in the config file, under Qobuz, I set the quality to 3, set my email and password.

Now, I can't download anything. In Windows Terminal and CMD, I have tried:
`rip -u https://open.qobuz.com/album/0060253780968`
Didn't work. Error: The term 'rip' is not recognized as the name of a cmdlet, function, script file, or operable program.

`py -m rip -u https://open.qobuz.com/album/0060253780968`
Didn't work. Error: No module named rip.

`py -m streamrip`
Didn't work. Error: No module named streamrip.__main__; 'streamrip' is a package and cannot be directly executed.

As I said, I am new to Python and command line, I don't know what to do next. Any help would be greatly appreciated.

**Comment by utubeonly007** [comment]
I think I figured out the problem. It was related to where pip.exe, pip3.exe and rip.exe are installed. The location is not PATH and needs to be added to PATH before I can run the commands. After I added the ...\Python\Python39\Scripts folder to PATH for my user account, it worked.

**Comment by nathom** [comment]
Yeah, I should probably mention PATH in the docs.
