### ISSUE TITLE
Couldn't fetch all the tracks from DZR.

### ISSUE THREAD

**Issue by VikasRana** [nathom/streamrip#65]
Example this URL : https://www.deezer.com/us/album/224391502

I am seeing all the tracks from my country (they are all playable) but SR was able to fetch only 25 of them.

Any way to custom set ARL or something?

**Comment by nathom** [comment]
This issue was fixed in `v0.5.1`. Run `pip3 install streamrip --upgrade` to update.

**Comment by nathom** [comment]
You need to upgrade to `Python >= 3.8`.

**Comment by Gamer4Life2020** [comment]
I have seen this as well but not sure if downgrading to 3.8 would help. It's fine in deemix but not streamrip. I get I can just use the other but I like this all in one so to speak.

![Streamrip error on year of the dragon](https://user-images.githubusercontent.com/36717721/117551472-cddeed80-b00b-11eb-8e5a-b077ce852d30.PNG)
![Streamrip](https://user-images.githubusercontent.com/36717721/117551478-d2a3a180-b00b-11eb-954b-ecbb4e94d84b.PNG)
![Deemix](https://user-images.githubusercontent.com/36717721/117551485-db947300-b00b-11eb-8ec6-868a86a57639.PNG)
![Deemix 1](https://user-images.githubusercontent.com/36717721/117551489-df27fa00-b00b-11eb-9e15-40ca41d6c0b6.PNG)
