### ISSUE TITLE
[FEATURE] Allow "discnumber" as a key in folder and track format

### ISSUE THREAD

**Issue by niessenty** [nathom/streamrip#652]
### Is the feature request related to a problem. Please describe it.

In multi-disc albums, currently there is (seemingly) no way to split tracks up by folder, either by appending something to the name, or allowing subfolders.

At best, it is irritating to have two files with the same track number in the same album folder, but it poses a more pertinent issue when an album may have the exact same track title on multiple discs, causing an overwrite.

### Describe the solution you would like.

I think it would be beneficial to add a "discnumber" key to the track naming format, which would allow one to split up tracks how they please.

As an example:
If I wanted separate folders, I could set the trackname to be "{discnumber:02}/{tracknumber:02} - {title}"
If I wanted them all to be in the same folder, I could use "{discnumber:02} - {tracknumber:02} - {title}"

### Describe alternatives you've considered.

I currently have a python script to rename files for me when I have downloaded them, but it still requires me to be careful when downloading albums with multiple discs, as I need to check if there are repeated track names.

**Comment by fominator** [comment]
Very strange that CRITICAL feature hadn't been added from the start.
