### ISSUE TITLE
[BUG] <i can't download>

### ISSUE THREAD

**Issue by NeryCast** [nathom/streamrip#675]
### Describe the bug

![cats](https://github.com/nathom/streamrip/assets/19565251/2ae399bd-d675-4d24-98d0-fc23f1d224a3)

### Command Used

```bash
./rip url -m 3 https://tidal.com/browse/album/360212374
```

### Debug Traceback

```text
A new version of streamrip v2.0.5 is available! Run pip3 install streamrip --upgrade to update.

#What's Changed

* Fix missing import
* Fix bug where max_cover_with doesnt work
* Add 2 zero padding for tracknumber by default
* Handle NonStreamableError for metadata parsing
* Fix tempfile issue on windows

**Full Changelog**: https://github.com/nathom/streamrip/compare/v2.0.4...v2.0.5
```

### Config File

```toml
original
```

### Operating System

Windows 10

### streamrip version

2.4

**Comment by nathom** [comment]
see error message

A new version of streamrip v2.0.5 is available! Run pip3 install streamrip --upgrade to update.
