### ISSUE TITLE
Deezer Track Title Characters

### ISSUE THREAD

**Issue by MrSpiffie** [nathom/streamrip#69]
Albums that contain track titles with question marks or hashtags seem to consistently be skipped for downloading:

rip -u https://www.deezer.com/us/album/339675 results in this:
![image](https://user-images.githubusercontent.com/63432120/117575818-7004e100-b0b1-11eb-9305-c7b6af2b6d0b.png)

I've seen this happen on at least ten different albums with Deezer, but the same album will have no issues on Qobuz.

**Comment by nathom** [comment]
See #15. It's unfixable. Sorry.
