### ISSUE TITLE
[FEATURE] Support for `auth_token` login on qobuz

### ISSUE THREAD

**Issue by barraIhsan** [nathom/streamrip#710]
### Is the feature request related to a problem. Please describe it.

Adding a `id` and `auth_token` would be nice. So we can login into qobuz without using a password.
Additional info: https://github.com/DJDoubleD/QobuzDownloaderX-MOD/wiki/Logging-In-(The-Alternate-Way)

### Describe the solution you would like.

I would like streamrip to add the ability to log into qobuz using `id` and `auth_token`

**Comment by RyanThaDude** [comment]
This is already added to the 2.x versions.

**Comment by barraIhsan** [comment]
wait, am I blind or ....
is there a documentation for using it/the commit?

**Comment by RyanThaDude** [comment]
Look at the configuration config.toml file as it has both options of login for qobuz

https://github.com/nathom/streamrip/blob/dev/streamrip/config.toml

**Comment by barraIhsan** [comment]
oh, thank you!
