### ISSUE TITLE
[Qobuz Discography] Download entire artist discography 

### ISSUE THREAD

**Issue by StryderGX** [nathom/streamrip#719]
### Is the feature request related to a problem. Please describe it.

May already be a thing but I haven't figure out how to make it work. But downloading an artist entire catalog from their discography page instead of needing to plug ing 50+ URLs for qobuz 

### Describe the solution you would like.

Listed above

**Comment by samuelmarinsoto** [comment]
I do this by using the artist url. Seems to work

**Comment by StryderGX** [comment]
> I do this by using the artist url. Seems to work

What command are you using and link? And also does it let you chose the quality as well? Been trying to get quality level 3 on most everything I can. Working on a large library for a revamped IPod Classic

**Comment by samuelmarinsoto** [comment]
`rip url https://play.qobuz.com/artist/724384'
I set the quality on the config file, its very well documented. You can also use `-q` to set the quality from the commandline

**Comment by StryderGX** [comment]
> `rip url https://play.qobuz.com/artist/724384` I set the quality on the config file, its very well documented. You can also use `-q` to set the quality from the commandline

Yeah think I was over complicating things a bit. Just saw a qobuz url and then the multiple url and thought that was it. Did some testing (on a raspberry pi in fact) last night with the quality modifiers and just the base url. I assumed (wrongly) it would just see the one url and maybe download the 5-6 songs on that page that were the most listened to, but nope seems to be working just fine.
