### ISSUE TITLE
Suggestion: Track verification on downloaded track and option to output to a log file

### ISSUE THREAD

**Issue by jgiokari** [nathom/streamrip#81]
I sometimes have the issue where some tracks of an album are partially downloaded i.e. 30 mb of 200 mb track.  The only way to fix this is to delete the track and re-download the album. If you don't delete the track it will skip it.  So some sort of file size comparison from the online track and downloaded track would be a good enhancement. 
Also an option to output to a log file would be good.

**Comment by nathom** [comment]
Please fill out a bug report with this issue. I need all of the relevant information to check out what's going on.
