### ISSUE TITLE
Bug: <A short and concise title>

### ISSUE THREAD

**Issue by jhoffmann** [nathom/streamrip#82]
## Bug Report

**Current Behavior**

Any rip commands exit with the error:

```
 D:\Music> rip config --open
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\rip.exe\__main__.py", line 4, in <module>
  File "c:\python38\lib\site-packages\streamrip\cli.py", line 12, in <module>
    from .clients import TidalClient
  File "c:\python38\lib\site-packages\streamrip\clients.py", line 14, in <module>
    from .constants import (
  File "c:\python38\lib\site-packages\streamrip\constants.py", line 88, in <module>
    id3.GP1,
AttributeError: module 'mutagen.id3' has no attribute 'GP1'
```

**`streamrip` Configuration File (find using `rip config -o`):**

There is no streamrip folder in users\username\appdata\local, and rip config -o gives the error above.

**Environment**

- `streamrip` version(s): 0.5.4
- Python version: 3.8.5
- OS: Windows 10

**Comment by nathom** [comment]
Try reinstalling mutagen:

```
pip3 uninstall mutagen -y; pip3 install mutagen --upgrade
``

**Comment by jhoffmann** [comment]
I found removing line 88 from constants.py did the trick and I'm able to download tracks from Tidal now without any issue.

I also don't see `GP1` referenced on https://mutagen.readthedocs.io/en/latest/api/id3_frames.html, though I do see a `GRP1`.

**Comment by nathom** [comment]
It seems like you have a different version of mutagen; ensure you have `1.45.1`. Also, removing line 88 will break the tags. Replacing it with `id3.GRP1` would be a better solution, since `GP1` and `GRP1` are aliases, if that works for you.

**Comment by jhoffmann** [comment]
Correct, I had mutagen 1.31.  Installed 1.45.1 and reverted constants.py to include GP1 and it works fine, thanks!
