### ISSUE TITLE
[Deezer] Improved Metadata

### ISSUE THREAD

**Issue by Morpheus2077** [nathom/streamrip#85]
• Remove TOTALTRACKS tag even as TRACKTOTAL
• Some tracks come with GENRE separated by ";" and not ","
• The COPYRIGHT tag is not correct, for example:
2021 Billie Eilish, instead of © 2021 Darkroom/Interscope Records
• Remove all zeros before numbers in tags (track, disc, trackTotal, discTotal)
• Default quality of artworks is 1200×1200
• Add an option to remove lyrics tag from tracks metadata, if possible customize all tags

**Comment by nathom** [comment]
Use the Bug Report or Feature Request Template please.
