### ISSUE TITLE
Tidal search forces Qobuz login

### ISSUE THREAD

**Issue by BobRock55** [nathom/streamrip#97]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

Streamrip command for Tidal search prompts Qobuz credentials ?

```
$ rip search  tidal 'eagles'
streamrip is up-to-date!
Logging into qobuz
Enter Qobuz email:
```

**Command used:**

```bash
rip search  tidal 'eagles'
```

**Expected behavior**

**`streamrip` Configuration File (find using `rip config -o`):**

```yaml
# Paste the contents of config.yaml here
# REMOVE YOUR CREDENTIALS
your:
    - config
    - file
```

**Environment**

- `streamrip` version(s): [e.g. v0.5.2]
- Python version: [e.g. 3.8]
- OS: [e.g. OSX 10.13.4, Windows 10]

**Traceback**
```bash
# Paste the text that Python dumped on the error here
# Delete this section if there was no traceback
```

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nathom** [comment]
You need to do `rip search --source tidal 'eagles'`. See the help page at `rip search --help` or in the wiki.

**Comment by BobRock55** [comment]
rip search --source tidal 'eagles' or rip search -s tidal 'eagles' works same after credential reset (rip config --tidal)
Thanks for the help.
