### ISSUE TITLE
Feature Request: Check for Missing Tracks

### ISSUE THREAD

**Issue by jcpit** [nathom/streamrip#98]
Sometimes when downloading it's unable to download some tracks.
e.g - _**Track The Prodigy - Voodoo People is not available for download, skipping.**_

If I run it again a little later, those missing tracks are downloaded eventually.

It would be great if there was a function that would look in the database and check to see if there are any missing tracks from the previous downloads. Like a 'repair' function, or something of that description.

**Comment by nathom** [comment]
Is the issue only for deezer downloads?

**Comment by jcpit** [comment]
It's the only one I've been using so couldn't tell you unfortunately.

**Comment by Gamer4Life2020** [comment]
Not to step on Nathom's toes and I love streamrip, being able to get from multiple sources in one app.
I have had this issue and it doesn't happen in other Deezer downloaders, unless the track is actually pulled by the label.
Even if a track isn't available in whatever country it normally is able to get it, unlike Qobuz/Tidal. They seem more strict in how they release. Try deemix if you can find it as it was DCMAed and still around but harder to get.

I'm no programmer and no idea on how they do it or what to look for, but if wanted I can send Nathom the copy I have and they  can look into the issue if wanted.

<img width="1044" alt="Voodoo People - Deezer" src="https://user-images.githubusercontent.com/36717721/123321714-f4dc7a80-d4f8-11eb-9b6c-9483154b36a5.PNG">

**Comment by jcpit** [comment]
I've used deemon with deemix with no issues.
I prefer the album selection stuff with streamrip.

Hopefully can be fixed up.

**Comment by Gamer4Life2020** [comment]
> I've used deemon with deemix with no issues.
> I prefer the album selection stuff with streamrip.
> 
> Hopefully can be fixed up.

Cool, yea I just wound out about deemix for the automation. Yea, like streamrip most of all the ones out too, but has the others as a backup.

**Comment by nathom** [comment]
Implemented in `v0.7`. Thanks for the suggestion!
